/**
 * CE.5 — Cross-RMN Feed Export service.
 *
 * Generates inventory-aware product feeds for Google Merchant Center (GMC)
 * and Meta Product Catalog. Both formats apply CE.1 FeedTransformRule
 * transforms before exporting so the master catalog is automatically
 * channel-correct.
 *
 * Inventory-aware: products below OUT_OF_STOCK_THRESHOLD get
 * availability=out_of_stock even if they have an active ChannelListing.
 *
 * GMC XML format: https://support.google.com/merchants/answer/7052112
 * Meta JSON format: https://developers.facebook.com/docs/marketing-api/catalog/
 */

import type { PrismaClient } from '@nexus/database'
import { evaluateRules } from './feed-transform.service.js'
import { logger } from '../../utils/logger.js'

const OUT_OF_STOCK_THRESHOLD = 0

// ── Types ──────────────────────────────────────────────────────────────────

export interface FeedProduct {
  id: string
  sku: string
  name: string
  brand: string | null
  description: string | null
  ean: string | null
  upc: string | null
  basePrice: number
  totalStock: number
  productType: string | null
  imageUrl: string | null
  availability: 'in stock' | 'out of stock'
  condition: 'new'
  transformedFields: Record<string, string>
}

export interface FeedExportSummary {
  total: number
  inStock: number
  outOfStock: number
  channel: 'GMC' | 'META'
  generatedAt: string
}

// ── Data loader ────────────────────────────────────────────────────────────

async function loadFeedProducts(
  prisma: PrismaClient,
  channel: 'GMC' | 'META',
  filters: { limit?: number } = {},
): Promise<FeedProduct[]> {
  const products = await prisma.product.findMany({
    where: {
      status: { not: 'INACTIVE' },
      deletedAt: null,
    } as never,
    select: {
      id: true,
      sku: true,
      name: true,
      brand: true,
      description: true,
      ean: true,
      upc: true,
      basePrice: true,
      totalStock: true,
      productType: true,
    },
    take: filters.limit ?? 10000,
    orderBy: { updatedAt: 'desc' },
  })

  const feedChannel = channel === 'GMC' ? 'AMAZON' : 'AMAZON'

  const result: FeedProduct[] = []
  for (const p of products) {
    let transformedFields: Record<string, string> = {}
    try {
      const pkg = await evaluateRules(prisma, p as Record<string, unknown>, feedChannel, null)
      transformedFields = pkg.resolved
    } catch {
      // Non-fatal: use raw fields
    }

    result.push({
      id: p.id,
      sku: p.sku,
      name: transformedFields.title ?? p.name,
      brand: p.brand,
      description: transformedFields.description ?? p.description,
      ean: p.ean,
      upc: p.upc,
      basePrice: Number(p.basePrice as unknown as { toString(): string }),
      totalStock: p.totalStock,
      productType: p.productType,
      imageUrl: null, // image linking deferred — requires MediaAsset relation
      availability: p.totalStock > OUT_OF_STOCK_THRESHOLD ? 'in stock' : 'out of stock',
      condition: 'new',
      transformedFields,
    })
  }

  return result
}

// ── GMC XML ────────────────────────────────────────────────────────────────

function escapeXml(str: string | null | undefined): string {
  if (!str) return ''
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export async function exportGMCFeed(
  prisma: PrismaClient,
  filters: { limit?: number } = {},
): Promise<{ xml: string; summary: FeedExportSummary }> {
  const products = await loadFeedProducts(prisma, 'GMC', filters)

  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss xmlns:g="http://base.google.com/ns/1.0" version="2.0">',
    '  <channel>',
    '    <title>Xavia Product Feed</title>',
    '    <link>https://xavia.it</link>',
    '    <description>Google Merchant Center product feed generated by Nexus</description>',
  ]

  for (const p of products) {
    // Google product category for motorcycle gear
    const gpCat = '5613' // Vehicles & Parts > Vehicle Parts & Accessories > Motorcycle Parts
    const price = p.basePrice.toFixed(2)

    lines.push('    <item>')
    lines.push(`      <g:id>${escapeXml(p.sku)}</g:id>`)
    lines.push(`      <g:title>${escapeXml(p.name)}</g:title>`)
    lines.push(`      <g:description>${escapeXml(p.description ?? p.name)}</g:description>`)
    lines.push(`      <g:link>https://xavia.it/products/${escapeXml(p.sku)}</g:link>`)
    if (p.imageUrl) {
      lines.push(`      <g:image_link>${escapeXml(p.imageUrl)}</g:image_link>`)
    }
    lines.push(`      <g:availability>${p.availability}</g:availability>`)
    lines.push(`      <g:price>${price} EUR</g:price>`)
    lines.push(`      <g:brand>${escapeXml(p.brand ?? 'Xavia')}</g:brand>`)
    lines.push(`      <g:condition>${p.condition}</g:condition>`)
    lines.push(`      <g:google_product_category>${gpCat}</g:google_product_category>`)
    if (p.productType) {
      lines.push(`      <g:product_type>${escapeXml(p.productType)}</g:product_type>`)
    }
    if (p.ean) lines.push(`      <g:gtin>${escapeXml(p.ean)}</g:gtin>`)
    if (p.upc) lines.push(`      <g:mpn>${escapeXml(p.upc)}</g:mpn>`)
    // Custom labels from transform rules
    if (p.transformedFields.custom_label_0) {
      lines.push(`      <g:custom_label_0>${escapeXml(p.transformedFields.custom_label_0)}</g:custom_label_0>`)
    }
    lines.push('    </item>')
  }

  lines.push('  </channel>')
  lines.push('</rss>')

  const inStock = products.filter((p) => p.availability === 'in stock').length

  return {
    xml: lines.join('\n'),
    summary: {
      total: products.length,
      inStock,
      outOfStock: products.length - inStock,
      channel: 'GMC',
      generatedAt: new Date().toISOString(),
    },
  }
}

// ── Meta Catalog JSON ──────────────────────────────────────────────────────

interface MetaProduct {
  id: string
  title: string
  description: string
  price: string // "99.99 EUR"
  availability: 'in stock' | 'out of stock'
  condition: 'new' | 'used' | 'refurbished'
  link: string
  image_link: string
  brand: string
  retailer_id: string
  category?: string
}

export async function exportMetaCatalog(
  prisma: PrismaClient,
  filters: { limit?: number } = {},
): Promise<{ items: MetaProduct[]; summary: FeedExportSummary }> {
  const products = await loadFeedProducts(prisma, 'META', filters)

  const items: MetaProduct[] = products.map((p) => ({
    id: p.sku,
    retailer_id: p.sku,
    title: p.name,
    description: (p.description ?? p.name).slice(0, 9999),
    price: `${p.basePrice.toFixed(2)} EUR`,
    availability: p.availability,
    condition: p.condition,
    link: `https://xavia.it/products/${encodeURIComponent(p.sku)}`,
    image_link: p.imageUrl ?? '',
    brand: p.brand ?? 'Xavia',
    ...(p.productType ? { category: p.productType } : {}),
  }))

  const inStock = items.filter((i) => i.availability === 'in stock').length

  return {
    items,
    summary: {
      total: items.length,
      inStock,
      outOfStock: items.length - inStock,
      channel: 'META',
      generatedAt: new Date().toISOString(),
    },
  }
}
