/**
 * P3b S5 (docs/attributes/PLAN.md §10.9) — the reviewed cleanup of the shared attribute set: one proposal row per code.
 *
 * Made from the attribute-scope study's classification (appendix A / `classification.tsv`, the 242 shared attributes of
 * 2026-09-10): its three classes, with channel-specific rows split by the channel that declares them (no Amazon field →
 * eBay; `shopify_product_type` → Shopify; otherwise Amazon: 69 / 4 / 1, as the study counts) and unused-or-duplicate rows
 * split by the study's reason (a same fact / "derive from" → duplicate, the rest → not relevant). Codes and classes only:
 * no product data. `sameFactAs` lists the other attributes of the set the study names as the same fact.
 *
 * What each group proposes: core → stays on Shared; amazon / ebay / shopify → placed on that channel; duplicate and
 * not relevant → archived (values and links kept; S9 merges duplicates). Nothing applies without the Owner's word, per
 * business, group by group.
 */
export type PlacementProposalGroup = 'core' | 'amazon' | 'ebay' | 'shopify' | 'duplicate' | 'not-relevant'
export interface PlacementProposalRow { code: string; group: PlacementProposalGroup; sameFactAs?: string[] }

export const PLACEMENT_PROPOSAL_REVISION = '2026-09-26.1'

/** Review order: the groups as the Owner sees them. */
export const PLACEMENT_PROPOSAL_GROUPS: readonly PlacementProposalGroup[] = ['core', 'amazon', 'ebay', 'shopify', 'duplicate', 'not-relevant']

/**
 * The four rows where the study and the concept catalogue (P3) disagree — shown to the Owner first. The concept list
 * adopts them (`certification` ← `ceCertification`, `lining` ← `lining_description`, `theme` ← `theme`, and
 * `collar_style` is `neckline`'s alternative code); the study calls them a duplicate or channel-specific. On Xavia
 * Racing (2026-09-26) three are linked; `collar_style` is not (the business also has `neckline`, which was linked).
 */
export const PLACEMENT_PROPOSAL_DISPUTED: readonly string[] = ['ceCertification', 'collar_style', 'lining_description', 'theme']

export const PLACEMENT_PROPOSAL: readonly PlacementProposalRow[] = [
  { code: "accepted_voltage_frequency", group: "amazon", sameFactAs: ["power_plug_type"] },
  { code: "additional_features", group: "duplicate", sameFactAs: ["special_feature"] },
  { code: "age_range_description", group: "core", sameFactAs: ["compliance_age_range"] },
  { code: "apparel_closure_orientation", group: "amazon", sameFactAs: ["closure"] },
  { code: "apparel_fabric_stretch", group: "amazon", sameFactAs: ["fabric_stretchability"] },
  { code: "apparel_fabric_weight_class", group: "amazon" },
  { code: "apparel_size__height_type", group: "amazon", sameFactAs: ["bottoms_size__height_type", "size"] },
  { code: "apparel_size__size_class", group: "amazon", sameFactAs: ["bottoms_size__size_class", "garment_size_country"] },
  { code: "apparel_size__size_to", group: "amazon", sameFactAs: ["size"] },
  { code: "armorType", group: "core", sameFactAs: ["garmentClass", "impactProtectors", "protection"] },
  { code: "athlete", group: "not-relevant" },
  { code: "auto_part_position", group: "amazon" },
  { code: "automotive_fit_type", group: "amazon", sameFactAs: ["compatibility_options"] },
  { code: "band", group: "not-relevant" },
  { code: "batteries_included", group: "amazon", sameFactAs: ["batteries_required"] },
  { code: "batteries_required", group: "amazon", sameFactAs: ["batteries_included", "contains_battery_or_cell"] },
  { code: "battery__cell_composition", group: "not-relevant" },
  { code: "battery__cell_composition_other_than_listed", group: "not-relevant" },
  { code: "battery__iec_code", group: "not-relevant" },
  { code: "battery__weightUnit", group: "not-relevant", sameFactAs: ["battery__weightValue"] },
  { code: "battery__weightValue", group: "not-relevant", sameFactAs: ["battery__weightUnit"] },
  { code: "battery_contains_free_unabsorbed_liquid", group: "not-relevant" },
  { code: "battery_installation_device_type", group: "not-relevant" },
  { code: "body_type", group: "amazon", sameFactAs: ["target_gender", "type"] },
  { code: "bottoms_size__height_type", group: "amazon", sameFactAs: ["apparel_size__height_type"] },
  { code: "bottoms_size__inseam_size", group: "amazon", sameFactAs: ["inseamValue"] },
  { code: "bottoms_size__size_class", group: "amazon", sameFactAs: ["apparel_size__size_class"] },
  { code: "bottoms_size__size_to", group: "amazon", sameFactAs: ["apparel_size__size_to"] },
  { code: "bottoms_size__waist_size", group: "amazon", sameFactAs: ["waist__sizeValue"] },
  { code: "care_instructions", group: "core" },
  { code: "ceCertification", group: "duplicate", sameFactAs: ["garmentClass", "glove_standard", "ppeCategory", "regulatory_compliance_certification"] },
  { code: "chestUnit", group: "core", sameFactAs: ["chestValue"] },
  { code: "chestValue", group: "core", sameFactAs: ["chestUnit"] },
  { code: "climate_suitability", group: "amazon", sameFactAs: ["seasons", "temperature_rating", "water_resistance_level"] },
  { code: "closure", group: "core", sameFactAs: ["apparel_closure_orientation", "compliance_fastening_method"] },
  { code: "coat_silhouette_type", group: "amazon" },
  { code: "coat_weather_protection", group: "amazon", sameFactAs: ["has_coat_weather_resistance", "water_resistance_level"] },
  { code: "collar_style", group: "duplicate", sameFactAs: ["neckline"] },
  { code: "collection_item", group: "amazon" },
  { code: "color", group: "core", sameFactAs: ["color__standardized_values", "exact_color", "specific_color"] },
  { code: "color__standardized_values", group: "duplicate", sameFactAs: ["color"] },
  { code: "compatibility_options", group: "amazon", sameFactAs: ["automotive_fit_type"] },
  { code: "compliance_age_range", group: "duplicate", sameFactAs: ["age_range_description"] },
  { code: "compliance_down_plumage_weight", group: "not-relevant" },
  { code: "compliance_embellishment_feature", group: "duplicate", sameFactAs: ["embellishment_feature"] },
  { code: "compliance_fastening_method", group: "duplicate", sameFactAs: ["closure"] },
  { code: "compliance_is_furskin_present", group: "duplicate", sameFactAs: ["fur"] },
  { code: "compliance_is_handmade", group: "not-relevant", sameFactAs: ["handmade_classification"] },
  { code: "compliance_other_material_additions", group: "not-relevant", sameFactAs: ["material"] },
  { code: "compliance_outer_surface_material", group: "duplicate", sameFactAs: ["material", "outer"] },
  { code: "compliance_printing_method", group: "not-relevant" },
  { code: "compliance_suit_included_components", group: "duplicate", sameFactAs: ["included_components", "number_of_pieces"] },
  { code: "compliance_suit_yarn_diameter", group: "not-relevant" },
  { code: "compliance_weave_type", group: "duplicate", sameFactAs: ["weave_type"] },
  { code: "compliance_wool_type", group: "not-relevant" },
  { code: "configuration", group: "not-relevant" },
  { code: "contains_battery_or_cell", group: "not-relevant", sameFactAs: ["batteries_required"] },
  { code: "countryOfOrigin", group: "core" },
  { code: "cup", group: "not-relevant" },
  { code: "customer_package_type", group: "amazon", sameFactAs: ["packageType"] },
  { code: "declarationOfConformityUrl", group: "core", sameFactAs: ["regulatory_compliance_certification"] },
  { code: "department", group: "amazon", sameFactAs: ["age_range_description", "target_gender"] },
  { code: "edition", group: "not-relevant" },
  { code: "embellishment_feature", group: "amazon", sameFactAs: ["compliance_embellishment_feature"] },
  { code: "eu_spare_part_availability_durationUnit", group: "amazon", sameFactAs: ["eu_spare_part_availability_durationValue"] },
  { code: "eu_spare_part_availability_durationValue", group: "amazon", sameFactAs: ["eu_spare_part_availability_durationUnit"] },
  { code: "eu_toys_safety_directive_age_warning", group: "amazon", sameFactAs: ["eu_toys_safety_directive_warning"] },
  { code: "eu_toys_safety_directive_warning", group: "amazon", sameFactAs: ["eu_toys_safety_directive_age_warning"] },
  { code: "exact_color", group: "duplicate", sameFactAs: ["color", "specific_color"] },
  { code: "exact_material", group: "duplicate", sameFactAs: ["fabric_type", "material", "specific_material"] },
  { code: "fabric_distressing", group: "not-relevant" },
  { code: "fabric_stretchability", group: "duplicate", sameFactAs: ["apparel_fabric_stretch"] },
  { code: "fabric_type", group: "core", sameFactAs: ["exact_material", "inner", "material", "outer", "specific_material", "weave_type"] },
  { code: "fabric_wash", group: "not-relevant" },
  { code: "fashion_decade", group: "not-relevant" },
  { code: "fc_shelf_lifeUnit", group: "not-relevant", sameFactAs: ["fc_shelf_lifeValue"] },
  { code: "fc_shelf_lifeValue", group: "not-relevant", sameFactAs: ["fc_shelf_lifeUnit"] },
  { code: "fit_to_size_sentiment", group: "amazon", sameFactAs: ["fit_type"] },
  { code: "fit_type", group: "core", sameFactAs: ["fit_to_size_sentiment"] },
  { code: "flavor", group: "not-relevant" },
  { code: "formality_level", group: "not-relevant" },
  { code: "front_pocket_count", group: "duplicate", sameFactAs: ["has_pockets", "number_of_pockets"] },
  { code: "front_style", group: "not-relevant" },
  { code: "fur", group: "amazon", sameFactAs: ["compliance_is_furskin_present"] },
  { code: "garmentClass", group: "core", sameFactAs: ["ceCertification", "regulatory_compliance_certification"] },
  { code: "garment_size_country", group: "core", sameFactAs: ["apparel_size__size_class", "bottoms_size__size_class"] },
  { code: "ghs", group: "not-relevant", sameFactAs: ["ghs_chemical_h_code", "hazmat", "hazmatClass"] },
  { code: "ghs_chemical_h_code", group: "not-relevant", sameFactAs: ["ghs"] },
  { code: "glove_protection_level", group: "core", sameFactAs: ["glove_standard"] },
  { code: "glove_standard", group: "core", sameFactAs: ["glove_protection_level", "knuckle_impact_protection", "regulatory_compliance_certification"] },
  { code: "glove_type", group: "amazon", sameFactAs: ["item_type_name"] },
  { code: "gpsr_safety_attestation", group: "amazon", sameFactAs: ["declarationOfConformityUrl"] },
  { code: "grip", group: "not-relevant" },
  { code: "grit", group: "not-relevant" },
  { code: "hand_orientation", group: "amazon" },
  { code: "handmade_classification", group: "not-relevant", sameFactAs: ["compliance_is_handmade"] },
  { code: "has_coat_weather_resistance", group: "duplicate", sameFactAs: ["coat_weather_protection", "water_resistance_level"] },
  { code: "has_less_than_30_percent_state_of_charge", group: "not-relevant" },
  { code: "has_multiple_battery_powered_components", group: "not-relevant" },
  { code: "has_pockets", group: "duplicate", sameFactAs: ["front_pocket_count", "number_of_pockets"] },
  { code: "has_replaceable_battery", group: "not-relevant" },
  { code: "hazmat", group: "not-relevant", sameFactAs: ["ghs", "hazmatClass", "supplier_declared_dg_hz_regulation"] },
  { code: "hazmatClass", group: "not-relevant", sameFactAs: ["ghs", "hazmat", "supplier_declared_dg_hz_regulation"] },
  { code: "hazmatUnNumber", group: "not-relevant", sameFactAs: ["ghs", "hazmat"] },
  { code: "hsCode", group: "core" },
  { code: "impactProtectors", group: "core", sameFactAs: ["armorType", "protection"] },
  { code: "included_components", group: "core", sameFactAs: ["compliance_suit_included_components", "number_of_items", "number_of_pieces"] },
  { code: "inner", group: "core", sameFactAs: ["lining_description", "material"] },
  { code: "inseamUnit", group: "core", sameFactAs: ["inseamValue"] },
  { code: "inseamValue", group: "core", sameFactAs: ["bottoms_size__inseam_size", "size"] },
  { code: "is_assembly_required", group: "amazon" },
  { code: "is_battery_non_spillable", group: "not-relevant" },
  { code: "is_expiration_dated_product", group: "amazon", sameFactAs: ["product_expiration_type"] },
  { code: "is_fragile", group: "amazon" },
  { code: "is_green_purchasing_law_compliant", group: "not-relevant" },
  { code: "is_oem_sourced_product", group: "not-relevant" },
  { code: "is_this_product_subject_to_buyer_age_restrictions", group: "amazon" },
  { code: "item_display_dimensions__depthUnit", group: "not-relevant", sameFactAs: ["item_display_dimensions__depthValue"] },
  { code: "item_display_dimensions__depthValue", group: "not-relevant" },
  { code: "item_display_dimensions__diameterUnit", group: "not-relevant", sameFactAs: ["item_display_dimensions__diameterValue"] },
  { code: "item_display_dimensions__diameterValue", group: "not-relevant" },
  { code: "item_length_description", group: "core", sameFactAs: ["length", "shoulder_to_bottom_hem_lengthValue", "width"] },
  { code: "item_package_quantity", group: "duplicate", sameFactAs: ["item_specific_quantity", "number_of_items", "package_contains_sku", "unit_count"] },
  { code: "item_shape", group: "not-relevant" },
  { code: "item_specific_quantity", group: "ebay", sameFactAs: ["number_of_items", "unit_count"] },
  { code: "item_specific_unit", group: "ebay", sameFactAs: ["unit_count__type"] },
  { code: "item_type_name", group: "core", sameFactAs: ["glove_type", "shopify_product_type", "suit_type", "type"] },
  { code: "jacket__decimal_value", group: "amazon", sameFactAs: ["size"] },
  { code: "jacket__string_value", group: "amazon", sameFactAs: ["size"] },
  { code: "jacket__unit", group: "amazon", sameFactAs: ["size"] },
  { code: "knuckle_impact_protection", group: "core", sameFactAs: ["glove_standard", "impactProtectors"] },
  { code: "language", group: "amazon" },
  { code: "league_name", group: "not-relevant" },
  { code: "leg", group: "not-relevant" },
  { code: "leg__decimal_value", group: "not-relevant" },
  { code: "leg__unit", group: "not-relevant" },
  { code: "leg_hem_opening_widthUnit", group: "amazon", sameFactAs: ["leg_hem_opening_widthValue"] },
  { code: "leg_hem_opening_widthValue", group: "amazon", sameFactAs: ["leg_hem_opening_widthUnit"] },
  { code: "length", group: "duplicate", sameFactAs: ["item_length_description", "width"] },
  { code: "lens", group: "not-relevant" },
  { code: "lens__color", group: "not-relevant" },
  { code: "lens__widthUnit", group: "not-relevant" },
  { code: "lens__widthValue", group: "not-relevant" },
  { code: "lifestyle", group: "amazon", sameFactAs: ["sport_type", "style"] },
  { code: "lining_description", group: "amazon", sameFactAs: ["inner"] },
  { code: "lithium_battery__energy_contentUnit", group: "not-relevant" },
  { code: "lithium_battery__energy_contentValue", group: "not-relevant" },
  { code: "lithium_battery__packaging", group: "not-relevant" },
  { code: "lithium_battery__weightUnit", group: "not-relevant" },
  { code: "lithium_battery__weightValue", group: "not-relevant" },
  { code: "manufacturer_warranty", group: "core", sameFactAs: ["warranty_description"] },
  { code: "material", group: "core", sameFactAs: ["compliance_outer_surface_material", "exact_material", "fabric_type", "outer", "specific_material"] },
  { code: "metal_type", group: "not-relevant" },
  { code: "model_name", group: "core", sameFactAs: ["model_number"] },
  { code: "model_number", group: "core", sameFactAs: ["model_name", "part_number"] },
  { code: "neckline", group: "core", sameFactAs: ["collar_style"] },
  { code: "non_lithium_battery_energy_content", group: "not-relevant" },
  { code: "non_lithium_battery_energy_content__unit", group: "not-relevant" },
  { code: "non_lithium_battery_packaging", group: "not-relevant" },
  { code: "notifiedBodyName", group: "core", sameFactAs: ["notifiedBodyNumber"] },
  { code: "notifiedBodyNumber", group: "core", sameFactAs: ["declarationOfConformityUrl", "notifiedBodyName", "regulatory_compliance_certification"] },
  { code: "num_batteries", group: "not-relevant" },
  { code: "number_of_items", group: "core", sameFactAs: ["item_package_quantity", "item_specific_quantity", "number_of_pieces", "unit_count"] },
  { code: "number_of_lithium_ion_cells", group: "not-relevant" },
  { code: "number_of_lithium_metal_cells", group: "not-relevant" },
  { code: "number_of_pieces", group: "duplicate", sameFactAs: ["included_components", "number_of_items"] },
  { code: "number_of_pockets", group: "amazon", sameFactAs: ["front_pocket_count", "has_pockets"] },
  { code: "oem_equivalent_part_number", group: "not-relevant", sameFactAs: ["part_number"] },
  { code: "outer", group: "duplicate", sameFactAs: ["compliance_outer_surface_material", "fabric_type", "material"] },
  { code: "packageDimensionUnit", group: "core" },
  { code: "packageHeight", group: "core" },
  { code: "packageLength", group: "core" },
  { code: "packageType", group: "ebay", sameFactAs: ["customer_package_type"] },
  { code: "packageWeightUnit", group: "core" },
  { code: "packageWeightValue", group: "core" },
  { code: "packageWidth", group: "core" },
  { code: "package_contains_sku", group: "amazon", sameFactAs: ["item_package_quantity"] },
  { code: "package_level", group: "amazon" },
  { code: "pants_form_type", group: "amazon" },
  { code: "part_number", group: "not-relevant", sameFactAs: ["model_number"] },
  { code: "pattern", group: "core", sameFactAs: ["pattern_type"] },
  { code: "pattern_type", group: "duplicate", sameFactAs: ["pattern"] },
  { code: "platform_for_display", group: "not-relevant" },
  { code: "pocket_description", group: "amazon", sameFactAs: ["number_of_pockets"] },
  { code: "power_plug_type", group: "amazon", sameFactAs: ["accepted_voltage_frequency"] },
  { code: "ppeCategory", group: "core", sameFactAs: ["ceCertification", "garmentClass", "regulatory_compliance_certification"] },
  { code: "product_expiration_type", group: "not-relevant", sameFactAs: ["is_expiration_dated_product"] },
  { code: "product_grade", group: "amazon" },
  { code: "protection", group: "duplicate", sameFactAs: ["armorType", "impactProtectors"] },
  { code: "regulatory_compliance_certification", group: "duplicate", sameFactAs: ["ceCertification", "garmentClass", "glove_standard", "ppeCategory"] },
  { code: "ring", group: "not-relevant" },
  { code: "rise__heightUnit", group: "core", sameFactAs: ["rise__heightValue"] },
  { code: "rise__heightValue", group: "core", sameFactAs: ["rise__style"] },
  { code: "rise__style", group: "amazon", sameFactAs: ["rise__heightValue"] },
  { code: "safety_data_sheet_url", group: "not-relevant", sameFactAs: ["declarationOfConformityUrl"] },
  { code: "scent", group: "not-relevant" },
  { code: "seasons", group: "core", sameFactAs: ["climate_suitability", "temperature_rating"] },
  { code: "shopify_product_type", group: "shopify", sameFactAs: ["item_type_name"] },
  { code: "shoulder_to_bottom_hem_lengthUnit", group: "core", sameFactAs: ["shoulder_to_bottom_hem_lengthValue"] },
  { code: "shoulder_to_bottom_hem_lengthValue", group: "core", sameFactAs: ["item_length_description"] },
  { code: "size", group: "core", sameFactAs: ["apparel_size__size_class", "garment_size_country"] },
  { code: "sleeve__length_description", group: "core", sameFactAs: ["sleeve__type"] },
  { code: "sleeve__type", group: "amazon", sameFactAs: ["sleeve__length_description"] },
  { code: "special_feature", group: "core", sameFactAs: ["additional_features", "water_resistance_level"] },
  { code: "special_size_type", group: "core" },
  { code: "specific_color", group: "duplicate", sameFactAs: ["color", "exact_color"] },
  { code: "specific_material", group: "duplicate", sameFactAs: ["exact_material", "material"] },
  { code: "specific_uses_for_product", group: "amazon", sameFactAs: ["sport_type"] },
  { code: "sport_type", group: "amazon", sameFactAs: ["lifestyle", "specific_uses_for_product"] },
  { code: "style", group: "core", sameFactAs: ["lifestyle", "theme"] },
  { code: "subject_character", group: "not-relevant" },
  { code: "suit_type", group: "amazon", sameFactAs: ["item_type_name"] },
  { code: "suitable_for", group: "duplicate", sameFactAs: ["department", "target_gender"] },
  { code: "supplier_declared_dg_hz_regulation", group: "amazon", sameFactAs: ["ghs", "hazmat", "hazmatClass"] },
  { code: "target_gender", group: "core", sameFactAs: ["athlete", "body_type", "department", "suitable_for"] },
  { code: "team_name", group: "not-relevant" },
  { code: "temperature_minimumUnit", group: "duplicate", sameFactAs: ["temperature_rating"] },
  { code: "temperature_minimumValue", group: "duplicate", sameFactAs: ["temperature_rating"] },
  { code: "temperature_rating", group: "amazon", sameFactAs: ["seasons", "temperature_minimumValue"] },
  { code: "theme", group: "amazon", sameFactAs: ["style"] },
  { code: "title_differentiation", group: "amazon" },
  { code: "type", group: "ebay", sameFactAs: ["item_type_name"] },
  { code: "ultraviolet_protection_factor", group: "not-relevant" },
  { code: "unit_count", group: "duplicate", sameFactAs: ["item_specific_quantity", "number_of_items"] },
  { code: "unit_count__type", group: "not-relevant", sameFactAs: ["item_specific_unit"] },
  { code: "vehicle_fitment__code", group: "amazon", sameFactAs: ["automotive_fit_type"] },
  { code: "vehicle_fitment__note", group: "amazon", sameFactAs: ["automotive_fit_type"] },
  { code: "vehicle_fitment__standard", group: "amazon", sameFactAs: ["automotive_fit_type"] },
  { code: "version_for_country", group: "not-relevant" },
  { code: "volume_capacity_nameUnit", group: "amazon", sameFactAs: ["volume_capacity_nameValue"] },
  { code: "volume_capacity_nameValue", group: "amazon", sameFactAs: ["volume_capacity_nameUnit"] },
  { code: "waistUnit", group: "duplicate", sameFactAs: ["waist__sizeUnit"] },
  { code: "waistValue", group: "duplicate", sameFactAs: ["waist__sizeValue"] },
  { code: "waist__sizeUnit", group: "core", sameFactAs: ["waist__sizeValue"] },
  { code: "waist__sizeValue", group: "core", sameFactAs: ["bottoms_size__waist_size", "waistValue", "waist__widthValue"] },
  { code: "waist__style", group: "amazon", sameFactAs: ["rise__style"] },
  { code: "waist__widthUnit", group: "duplicate", sameFactAs: ["waist__sizeUnit"] },
  { code: "waist__widthValue", group: "duplicate", sameFactAs: ["waist__sizeValue"] },
  { code: "warranty_description", group: "duplicate", sameFactAs: ["manufacturer_warranty"] },
  { code: "water_resistance_level", group: "core", sameFactAs: ["climate_suitability", "coat_weather_protection", "has_coat_weather_resistance"] },
  { code: "weave_type", group: "amazon", sameFactAs: ["compliance_weave_type", "fabric_type"] },
  { code: "width", group: "duplicate", sameFactAs: ["item_length_description", "length"] },
]

export function placementProposalFor(code: string): PlacementProposalRow | undefined {
  return PLACEMENT_PROPOSAL.find(row => row.code === code)
}
