/**
 * MCP full control P1 — the coverage map, in code: every file in apps/api/src/routes (images/ included) belongs to
 * ONE part of the MCP full control plan, or is kept away from Claude with a reason.
 *
 * Source: docs/mcp-full-control/sections/09-platform-and-coverage.md §1 (85 features, 199 route files, read on
 * origin/main 087224821). A file in several features has one owner here; `also` says what the others are. The three
 * GAP rows are owned as the plan settles them (§3 overlap 10): A+, Brand Story, SEO, relations and certificates by the
 * text part (03, phase 2), recovering a deleted product by the listings part (02).
 *
 * mcp-coverage.vitest.test.ts fails when a route file has no row (a feature nobody decided about) and when a row
 * names a file that is gone. A new route file gets a row in the same change: a part, or `excluded` with the reason.
 * "Never for Claude" (09 §2) is held for tools by agents/tool-never.vitest.test.ts.
 */

/** The parts of the plan (PLAN-2026-10-01.md), by section number. */
export const PLAN_PARTS = {
  '01': 'Ads on every channel and market',
  '02': 'Listings: products, publish, close, photos, listing price and stock',
  '03': 'Text: titles, bullets, descriptions, keywords, attributes',
  '04': 'Product ids and consistency',
  '05': 'The shared control layer: approvals, undo, businesses, audit, Claude’s door',
  '06': 'Every automation: rules, bid engines, schedules, the agent fleet',
  '07': 'Orders, shipping, returns, refunds, messages, reviews, invoices, customers',
  '08': 'Stock, warehouses, transfers, suppliers, purchase orders, costs, pricing',
  '09': 'Platform features and the factory',
} as const

export type PlanPart = keyof typeof PLAN_PARTS

/**
 * One route file: the part that owns it for Claude (`feature` is its row in 09 §1, `also` what other rows say), or
 * why it is kept from Claude.
 */
export type RouteCoverage =
  | { part: PlanPart; feature: number; also?: string }
  | { excluded: string; feature: number | null }

/** Keyed by the file's path under routes/, without `.routes.ts` (or `.ts`): `products`, `images/media-plan`. */
export const ROUTE_COVERAGE: Readonly<Record<string, RouteCoverage>> = {
  accounts: { part: '09', feature: 50, also: 'reads only; connect, revoke, grants and account writes are never for Claude (#51, #52)' },
  admin: { excluded: 'admin repair, purge, restore, backfill, probes and dead connections have no undo (09 §2)', feature: 81 },
  'advertising-ai': { part: '06', feature: 20 },
  'advertising-intel': { part: '01', feature: 17 },
  'automation-switch': { part: '06', feature: 20, also: "a person's engine switch in the Control Room; Claude moves it with turn-up / turn-down-automation (R16)" },
  advertising: { part: '01', feature: 17, also: 'its automation paths (rules, autopilot, dayparting) are the automation part, 06 (#20)' },
  'agent-fleet-approvals': { part: '05', feature: 45 },
  'approval-queue': { part: '05', feature: 45, also: 'the Approvals grid reads every request; Claude follows its own with approval-status and claude-activity' },
  'agent-fleet-assignments': { part: '06', feature: 44 },
  'agent-fleet-map': { part: '06', feature: 44 },
  'agent-fleet-timeline': { part: '06', feature: 44 },
  'agent-fleet-workers': { part: '06', feature: 44 },
  'agent-fleet-workflows': { part: '06', feature: 44 },
  'agent-fleet': { part: '06', feature: 44 },
  agents: { part: '05', feature: 45 },
  'ai-usage': { part: '09', feature: 59, also: 'usage read only; brand voices are the text part, 03 (#5); providers, budgets, switches never' },
  ai: { excluded: 'AI generation inside Nexus spends the Nexus AI budget; Claude writes its own text', feature: 16 },
  'amazon-ads-auth': { excluded: 'connecting the Amazon Ads account and its account-level live-write switch: a person in the browser (09 §2)', feature: 22 },
  'amazon-cockpit-publish': { part: '02', feature: 2 },
  'amazon-economics': { part: '09', feature: 75 },
  'amazon-financials': { part: '09', feature: 75 },
  'amazon-flat-file': { excluded: 'Owner rule 2026-09-29: never the old flat-file pages', feature: 14 },
  'amazon-listing-asin': { part: '04', feature: 9 },
  'amazon-notifications': { excluded: 'admin repair, purge, restore, backfill, probes and dead connections have no undo (09 §2)', feature: 81 },
  'amazon-orders-2026-probe': { excluded: 'admin repair, purge, restore, backfill, probes and dead connections have no undo (09 §2)', feature: 81 },
  'amazon-preflight': { part: '02', feature: 2 },
  'amazon-reports': { part: '09', feature: 75 },
  amazon: { part: '07', feature: 26, also: 'orders; the legacy pushes and manual syncs are excluded (#15)' },
  analytics: { part: '09', feature: 74 },
  'aplus-content': { part: '03', feature: 10, also: 'A+ content: phase 2 of the text part (plan §3 overlap 10)' },
  assets: { part: '09', feature: 67 },
  assortments: { part: '09', feature: 52, also: 'read only; every sharing change is never for Claude' },
  attributes: { part: '09', feature: 60 },
  'audit-log': { part: '09', feature: 78 },
  auth: { excluded: 'sign-in, passwords, 2FA, sessions, invitations, personal profile: never for Claude (09 §2)', feature: 55 },
  'brand-brain': { excluded: 'AI generation inside Nexus spends the Nexus AI budget; Claude writes its own text', feature: 16 },
  'brand-kit': { part: '09', feature: 25, also: 'read only first' },
  'brand-settings': { part: '09', feature: 47 },
  'brand-story': { part: '03', feature: 10, also: 'Brand Story: phase 2 of the text part (plan §3 overlap 10)' },
  'bulk-action-templates': { part: '09', feature: 70 },
  'bulk-automation-approvals': { part: '06', feature: 43 },
  'bulk-automation-rules': { part: '06', feature: 43 },
  'bulk-image-publish': { part: '02', feature: 3 },
  'bulk-operations': { part: '09', feature: 70 },
  'catalog-matrix': { part: '02', feature: 2 },
  'catalog-organize': { part: '03', feature: 7 },
  'catalog-safe': { part: '04', feature: 9 },
  'catalog-transfer': { part: '09', feature: 68, also: 'imports and exports (#68, #69); AI translate inside a transfer stays excluded (#16)' },
  catalog: { part: '02', feature: 1, also: 'the eBay catalog import is the ids part, 04 (#9)' },
  categories: { part: '09', feature: 62 },
  'cell-formula': { part: '09', feature: 63 },
  'channel-mapping-sets': { part: '09', feature: 63 },
  'channel-mapping': { part: '09', feature: 63 },
  'channel-publish': { part: '02', feature: 3 },
  'claude-control': { part: '05', feature: 45, also: 'Claude’s own levels, limits and brakes: set by people in Nexus, never offered to Claude as tools' },
  'cloudinary-webhook': { excluded: 'webhook receivers and health checks: machine to machine, nothing for a person or Claude', feature: 82 },
  'cockpit-telemetry': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  'connection-dependents': { excluded: 'admin repair, purge, restore, backfill, probes and dead connections have no undo (09 §2)', feature: 81 },
  connections: { part: '09', feature: 50 },
  'control-tower': { part: '08', feature: 35 },
  'customer-segments': { part: '07', feature: 31 },
  customers: { part: '07', feature: 31 },
  'cx-connect': { excluded: 'connect, reconnect, revoke, disconnect, refresh, app secrets: the account holder signs in in the browser (09 §2)', feature: 51 },
  'cx-connections': { part: '09', feature: 50, also: 'status and health read only; every connection write is never for Claude (#51)' },
  'cx-listing-issues': { part: '02', feature: 8 },
  'cx-quarantine': { part: '09', feature: 53, also: 'counts only; adopting a notice is never for Claude' },
  dashboard: { part: '09', feature: 73, also: 'saved views (#71) too; the stock-drift resync is 08, the circuit-breaker reset excluded (#80)' },
  'delist-cascade': { excluded: 'irreversible: hard delete and delist cascade (decision d5; never for Claude, 09 §2)', feature: 13 },
  'ebay-ads': { part: '01', feature: 18, also: 'its automation is the automation part, 06 (#20)' },
  'ebay-auth': { excluded: 'connect, reconnect, revoke, disconnect, refresh, app secrets: the account holder signs in in the browser (09 §2)', feature: 51 },
  'ebay-cockpit': { part: '02', feature: 2 },
  'ebay-description-push': { part: '03', feature: 6 },
  'ebay-description-themes': { part: '09', feature: 64 },
  'ebay-flat-file': { excluded: 'Owner rule 2026-09-29: never the old flat-file pages', feature: 14 },
  'ebay-notification': { excluded: 'eBay notice subscriptions (admin, #81) and the notice receiver (#82): machine to machine and platform-wide', feature: 81 },
  'ebay-orders': { part: '07', feature: 26 },
  'ebay-phase3': { part: '02', feature: 2 },
  'ebay-volume-pricing': { part: '08', feature: 41 },
  ebay: { part: '09', feature: 75, also: 'financials read only; the legacy sync, policy and diagnostic routes are excluded (#15), their policy reads used by 02' },
  'etsy-webhooks': { excluded: 'webhook receivers and health checks: machine to machine, nothing for a person or Claude', feature: 82 },
  etsy: { part: '07', feature: 26, also: 'orders; the manual syncs are excluded (#15)' },
  'export-wizard': { part: '09', feature: 69 },
  families: { part: '09', feature: 61 },
  'fba-inbound-v2': { part: '08', feature: 36 },
  'feed-export': { part: '09', feature: 24, also: 'read only first' },
  'feed-transform': { part: '09', feature: 24, also: 'read only first' },
  'field-links': { part: '09', feature: 63 },
  'flat-file-import': { excluded: 'Owner rule 2026-09-29: never the old flat-file pages', feature: 14 },
  'flat-file-pull-history': { excluded: 'Owner rule 2026-09-29: never the old flat-file pages', feature: 14 },
  'flat-file-unified': { excluded: 'Owner rule 2026-09-29: never the old flat-file pages', feature: 14 },
  forecast: { part: '08', feature: 38 },
  fulfillment: { part: '07', feature: 28, also: 'routing and shipping (#27, #28); inbound, purchase orders, suppliers, replenishment and FNSKU are 08 (#36–#39)' },
  'gtin-exemption': { part: '04', feature: 9 },
  health: { excluded: 'webhook receivers and health checks: machine to machine, nothing for a person or Claude', feature: 82 },
  'import-wizard': { part: '09', feature: 68 },
  inbox: { part: '09', feature: 76 },
  insights: { part: '09', feature: 72 },
  'inventory-sync-diagnostics': { part: '08', feature: 35 },
  inventory: { part: '08', feature: 33 },
  'job-monitor': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  'keyword-actions': { part: '01', feature: 17 },
  'listing-automation-rules': { part: '06', feature: 43 },
  'listing-content': { excluded: 'AI generation inside Nexus spends the Nexus AI budget; Claude writes its own text', feature: 16 },
  'listing-health': { part: '02', feature: 2 },
  'listing-images': { part: '02', feature: 3 },
  'listing-recovery': { part: '02', feature: 12, also: 'recover a deleted product (recover-product); the recycle-bin purge stays excluded (plan §3 overlap 10)' },
  'listing-wizard': { part: '02', feature: 2 },
  'listings-syndication': { part: '02', feature: 2 },
  listings: { excluded: 'legacy pushes and manual syncs, superseded by the studio publish path; syncs are cron work', feature: 15 },
  'live-read': { part: '03', feature: 5 },
  'mapping-propagation': { part: '09', feature: 63 },
  'marketing-automation': { part: '06', feature: 21 },
  'marketing-os': { part: '01', feature: 19, also: 'its rules and budget rebalance are the automation part, 06 (#20)' },
  marketing: { excluded: 'legacy marketing stub with no data', feature: 23 },
  marketplaces: { part: '09', feature: 49, also: 'the product-channel routes are the listings part, 02 (#2); marketplaces/seed is admin' },
  matrix: { part: '02', feature: 2 },
  mcp: { part: '05', feature: 46, also: 'Claude’s own door and access: never offered to Claude as tools' },
  mfa: { excluded: 'sign-in, passwords, 2FA, sessions, invitations, personal profile: never for Claude (09 §2)', feature: 55 },
  monitoring: { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  notifications: { part: '09', feature: 76 },
  'oauth-grants': { part: '05', feature: 46, also: 'Claude’s own door and access: never offered to Claude as tools' },
  oauth: { part: '05', feature: 46, also: 'Claude’s own door and access: never offered to Claude as tools' },
  'orders-reviews': { part: '07', feature: 30 },
  'orders-routing': { part: '07', feature: 27 },
  orders: { part: '07', feature: 26, also: 'the bulk hard delete stays excluded (#13)' },
  'outbound-latency': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  'outbound-queue': { part: '09', feature: 79 },
  outbound: { part: '09', feature: 79 },
  'pim-categories': { part: '09', feature: 62 },
  'pim-global': { part: '02', feature: 1 },
  'pim-mapping': { part: '09', feature: 63 },
  pim: { part: '02', feature: 1 },
  'pricing-rules': { part: '08', feature: 41 },
  pricing: { part: '08', feature: 41 },
  'product-certificates': { part: '03', feature: 11, also: 'certificates: the text part, phase 2 (plan §3 overlap 10)' },
  'product-channel-data': { part: '02', feature: 1 },
  'product-costs': { part: '08', feature: 40 },
  // origin/main #247 (merged 2026-10-02): the Products page's "New product" dialog creates a DRAFT — product create, the listings part.
  'product-create': { part: '02', feature: 1 },
  'product-enrichment': { excluded: 'AI generation inside Nexus spends the Nexus AI budget; Claude writes its own text', feature: 16 },
  'product-images-crud': { part: '02', feature: 3 },
  'product-relations': { part: '03', feature: 11, also: 'related products: the text part, phase 2 (plan §3 overlap 10)' },
  'product-seo': { part: '03', feature: 11, also: 'SEO fields: phase 2 of the text part (plan §3 overlap 10)' },
  'product-studio': { part: '02', feature: 2 },
  'product-translations': { part: '03', feature: 5 },
  'product-workflow': { part: '09', feature: 65 },
  'products-ai': { excluded: 'AI generation inside Nexus spends the Nexus AI budget; Claude writes its own text', feature: 16 },
  'products-bulk-save': { part: '02', feature: 1 },
  'products-catalog': { part: '02', feature: 1, also: 'status; tags and bundles are 09 (#66, bundles read only); the bulk hard delete stays excluded (#13)' },
  'products-images': { part: '02', feature: 3 },
  'products-search': { part: '02', feature: 1 },
  'products-sheet': { part: '03', feature: 5 },
  products: { part: '02', feature: 1 },
  profile: { excluded: 'sign-in, passwords, 2FA, sessions, invitations, personal profile: never for Claude (09 §2)', feature: 55 },
  'push-health': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  'push-latency': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  reconciliation: { part: '04', feature: 9 },
  'repricing-rules': { part: '06', feature: 42 },
  returns: { part: '07', feature: 29 },
  'review-inserts': { part: '07', feature: 30 },
  'review-send-windows': { part: '07', feature: 30 },
  reviews: { part: '07', feature: 30, also: 'the email suppression list stays excluded (#58)' },
  'saved-view-alerts': { part: '09', feature: 71 },
  'saved-view-persistence': { part: '09', feature: 71 },
  'scheduled-bulk-actions': { part: '06', feature: 43 },
  'scheduled-exports': { part: '09', feature: 69 },
  'scheduled-image-publishes': { part: '06', feature: 43 },
  'scheduled-imports': { part: '09', feature: 68 },
  'sendcloud-webhooks': { excluded: 'webhook receivers and health checks: machine to machine, nothing for a person or Claude', feature: 82 },
  'settings-audit': { part: '09', feature: 78 },
  'settings-privacy': { excluded: 'privacy: personal-data export, account deletion, retention, consent, suppressions: never for Claude (09 §2)', feature: 58 },
  'settings-webhooks': { excluded: 'outgoing webhooks send business data to any address: never for Claude (09 §2)', feature: 57 },
  'sheet-transfer': { part: '09', feature: 68 },
  'shopify-media': { part: '09', feature: 67 },
  'shopify-shadow-report': { excluded: 'platform operations (job monitor, queues, telemetry, circuit breakers) are platform-wide, not one business (09 §2)', feature: 80 },
  'shopify-webhooks': { excluded: 'webhook receivers and health checks: machine to machine, nothing for a person or Claude', feature: 82 },
  'stock-pool': { part: '08', feature: 34, also: 'pool grants to another business: read only, 09 (#52); every sharing change is never for Claude' },
  stock: { part: '08', feature: 33 },
  'studio-matrix': { part: '02', feature: 2 },
  'sync-control': { part: '08', feature: 35, also: 'per-listing control is the listings part, 02 (#2)' },
  'sync-logs': { part: '09', feature: 79, also: 'read only; saved searches (#71) and alert rules (#77) too; replay, purge and cron triggers excluded (#80)' },
  sync: { part: '02', feature: 8 },
  taxonomy: { part: '09', feature: 62 },
  team: { part: '09', feature: 54, also: 'read only; every change is never for Claude' },
  terminology: { part: '03', feature: 5 },
  'tier-pricing': { part: '08', feature: 41 },
  validation: { excluded: 'a helper with no routes', feature: null },
  'value-map': { part: '09', feature: 63 },
  'variant-transfer': { part: '09', feature: 68 },
  'wizard-templates': { part: '09', feature: 64 },
  'workflow-assignments': { part: '09', feature: 65 },
  workflows: { part: '09', feature: 65 },
  'workspace-invitations': { excluded: 'sign-in, passwords, 2FA, sessions, invitations, personal profile: never for Claude (09 §2)', feature: 55 },
  workspaces: { part: '09', feature: 47, also: 'business settings reads (#47) and team access read only (#54); create, rename, archive and every member change are never for Claude (#48)' },
  'images/amazon-images': { part: '02', feature: 3 },
  'images/amazon-media-workspace': { part: '02', feature: 3 },
  'images/channel-image-publish': { part: '02', feature: 3 },
  'images/ebay-media-workspace': { part: '02', feature: 3 },
  'images/images-workspace': { part: '02', feature: 3 },
  'images/media-plan': { part: '02', feature: 3 },
  'images/product-media': { part: '02', feature: 3 },
  'images/shopify-colour-products': { part: '02', feature: 4 },
  'images/shopify-content': { part: '03', feature: 5 },
  'images/shopify-linked-products': { part: '02', feature: 4 },
}

/**
 * The coverage key of a file under routes/, or null when it is not a route file: a test (`*.test.ts`, `__tests__/`)
 * or not TypeScript.
 */
export function routeKeyOf(relativePath: string): string | null {
  const path = relativePath.split('\\').join('/')
  if (!path.endsWith('.ts') || path.endsWith('.test.ts') || path.endsWith('.d.ts')) return null
  if (path.split('/').some((segment) => segment === '__tests__')) return null
  return path.replace(/\.routes\.ts$/, '').replace(/\.ts$/, '')
}

/** Route files with no row (`missing`), and rows that name no route file (`stale`). Both must be empty. */
export function coverageGaps(
  routeKeys: readonly string[],
  coverage: Readonly<Record<string, RouteCoverage>> = ROUTE_COVERAGE,
): { missing: string[]; stale: string[] } {
  const present = new Set(routeKeys)
  return {
    missing: [...present].filter((key) => !Object.prototype.hasOwnProperty.call(coverage, key)).sort(),
    stale: Object.keys(coverage).filter((key) => !present.has(key)).sort(),
  }
}
