/**
 * Additional DISTINCT automations — extends the registry with more unique
 * (signal → action) concepts on the live engine vocabulary. No threshold twins:
 * each is a different intent. Merged into AUTOMATIONS in automations.ts.
 */

import type { AutomationDef, ParamDef } from './automations'

const N = (p: Record<string, number | string>, k: string, d = 0) => { const v = Number(p[k]); return Number.isFinite(v) ? v : d }
const notify = (message: string) => ({ type: 'notify', target: 'operator', message })
const alert = (message: string) => ({ type: 'alert_operator', message })
const pPct = (key: string, label: string, def: number, hint?: string): ParamDef => ({ key, label, kind: 'pct', default: def, hint })
const pEur = (key: string, label: string, def: number, hint?: string): ParamDef => ({ key, label, kind: 'eur', default: def, hint })
const pDays = (key: string, label: string, def: number): ParamDef => ({ key, label, kind: 'days', default: def })
const pStep = (def: number): ParamDef => ({ key: 'step', label: 'Adjust by', kind: 'pct', default: def })
const pAcos = (def: number): ParamDef => ({ key: 'acos', label: 'ACOS threshold', kind: 'pct', default: def })
const pRoas = (key: string, label: string, def: number): ParamDef => ({ key, label, kind: 'roas', default: def })

export const MORE_AUTOMATIONS: AutomationDef[] = [
  // ── Low-CTR keyword lifecycle (distinct actions on the same signal) ─────
  { id: 'floor-low-ctr', name: 'Floor bids on low-CTR keywords', desc: 'Drop bids to the floor on keywords whose click-through rate is chronically low — keep presence, stop overpaying for impressions that don’t click.', category: 'Bidding', trigger: 'KEYWORD_LOW_CTR', params: [], build: () => ({ conditions: [], actions: [{ type: 'lower_bid_to_floor', reason: 'Chronically low CTR' }, notify('Low-CTR keywords dropped to floor')], maxExecutionsPerDay: 60 }) },
  { id: 'biddown-low-ctr', name: 'Bid down on low CTR', desc: 'Ease bids back on low-CTR keywords rather than flooring them — a gentler relevance correction.', category: 'Bidding', trigger: 'KEYWORD_LOW_CTR', params: [pStep(20)], build: (p) => ({ conditions: [], actions: [{ type: 'bid_down', target: 'keyword', percent: N(p, 'step', 20), reason: 'Low CTR' }, notify('Bids eased on low CTR')], maxExecutionsPerDay: 60 }) },
  { id: 'archive-low-ctr', name: 'Archive chronically low-CTR keywords', desc: 'Retire keywords whose CTR never recovers — they hurt account relevance.', category: 'Pruning', trigger: 'KEYWORD_LOW_CTR', params: [], build: () => ({ conditions: [], actions: [{ type: 'archive_keyword', reason: 'Chronically low CTR' }, notify('Low-CTR keyword archived')], maxExecutionsPerDay: 40 }) },
  { id: 'pause-adgroup-low-ctr', name: 'Pause ad group on low CTR', desc: 'Pause the ad group when its keyword CTR collapses — usually a targeting or creative mismatch.', category: 'Pruning', trigger: 'KEYWORD_LOW_CTR', params: [], build: () => ({ conditions: [], actions: [{ type: 'pause_ad_group', reason: 'Low CTR' }, notify('Ad group paused — low CTR')], maxExecutionsPerDay: 40 }) },

  // ── Wasted-spend keyword lifecycle (more distinct actions) ──────────────
  { id: 'biddown-wasted', name: 'Bid down on wasted spend', desc: 'Cut (don’t floor) bids on keywords spending without selling — a softer touch than flooring or archiving.', category: 'Bidding', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 10), pStep(25)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 10) * 100 }], actions: [{ type: 'bid_down', target: 'keyword', percent: N(p, 'step', 25), reason: 'Wasted spend' }, notify('Bids cut on wasted spend')], maxExecutionsPerDay: 80 }) },

  // ── Zero-impression keyword (distinct from "boost") ─────────────────────
  { id: 'rankdefend-no-impr', name: 'Rank-defend starved keywords', desc: 'Apply rank-defense bidding (not just a flat raise) to keywords with no impressions so they re-enter the auction competitively.', category: 'Bidding', trigger: 'KEYWORD_ZERO_IMPRESSIONS', params: [pStep(20)], build: (p) => ({ conditions: [], actions: [{ type: 'raise_bids_for_rank_defense', percent: N(p, 'step', 20) }, notify('Rank-defense applied to starved keywords')], maxExecutionsPerDay: 30 }) },

  // ── Underperforming target (distinct from pause-ad-group) ───────────────
  { id: 'archive-dead-target', name: 'Archive dead targets', desc: 'Archive keyword/ASIN targets that spent past your limit with no sales — clean the account, not just pause.', category: 'Pruning', trigger: 'AD_TARGET_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 30)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 30) * 100 }, { field: 'adTarget.salesCents', op: 'eq', value: 0 }], actions: [{ type: 'archive_keyword', reason: 'Dead target' }, notify('Dead target archived')], maxExecutionsPerDay: 50 }) },

  // ── Profit breach (distinct actions) ────────────────────────────────────
  { id: 'pause-adgroup-profit-breach', name: 'Pause ad group on profit breach', desc: 'Surgically pause the offending ad group (not the whole campaign) when ad spend beats true profit.', category: 'Profitability', trigger: 'AD_SPEND_PROFITABILITY_BREACH', params: [], build: () => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'pause_ad_group', reason: 'Margin-negative' }, notify('Ad group paused — margin-negative')], maxExecutionsPerDay: 20 }) },
  { id: 'floor-profit-breach', name: 'Floor bids on profit breach', desc: 'Crush bids to the floor when a campaign turns margin-negative — keep it alive but starve the spend.', category: 'Profitability', trigger: 'AD_SPEND_PROFITABILITY_BREACH', params: [], build: () => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'lower_bid_to_floor', reason: 'Margin-negative' }, notify('Bids floored — margin-negative')], maxExecutionsPerDay: 20 }) },

  // ── CVR drop (distinct actions) ─────────────────────────────────────────
  { id: 'floor-cvr-drop', name: 'Floor bids on conversion collapse', desc: 'Drop bids to the floor when conversion rate craters, so spend nearly stops until the listing/price/stock issue is fixed.', category: 'Conversion', trigger: 'CVR_DROP', params: [], build: () => ({ conditions: [], actions: [{ type: 'lower_bid_to_floor', reason: 'CVR collapse' }, notify('Bids floored — CVR collapse')], maxExecutionsPerDay: 20 }) },
  { id: 'trimbudget-cvr-drop', name: 'Trim budget on CVR drop', desc: 'Cut the daily budget when conversion rate drops so you waste less while the root cause is fixed.', category: 'Conversion', trigger: 'CVR_DROP', params: [pStep(20)], build: (p) => ({ conditions: [], actions: [{ type: 'adjust_ad_budget', percent: -N(p, 'step', 20), reason: 'CVR drop' }, notify('Budget trimmed — CVR drop')], maxExecutionsPerDay: 20 }) },

  // ── Budget (distinct mechanics) ─────────────────────────────────────────
  { id: 'setbudget-winners', name: 'Set fixed budget on winners', desc: 'Pin a generous fixed daily budget on campaigns clearing a ROAS bar (instead of a relative +%).', category: 'Budget', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', params: [{ key: 'roas', label: 'ROAS ≥', kind: 'roas', default: 4 }, pEur('budget', 'Set budget to (€/day)', 50)], build: (p) => ({ conditions: [{ field: 'campaign.roas', op: 'gte', value: N(p, 'roas', 4) }], actions: [{ type: 'set_daily_budget', budgetEur: N(p, 'budget', 50), reason: 'ROAS winner' }, notify('Fixed budget set on a winner')], maxExecutionsPerDay: 10, maxDailyAdSpendCentsEur: 30000 }) },
  { id: 'alert-budget-cap-approaching', name: 'Alert before monthly cap', desc: 'Warn you when month-to-date spend approaches your cap, so you can react before everything pauses.', category: 'Alerts', trigger: 'SCHEDULE', params: [pEur('threshold', 'Warn at spend (€)', 1800)], build: (p) => ({ conditions: [{ field: 'budget.monthlySpendCents', op: 'gte', value: N(p, 'threshold', 1800) * 100 }], actions: [alert('Monthly spend approaching your cap')], maxExecutionsPerDay: 24 }) },

  // ── Placement (distinct surface) ────────────────────────────────────────
  { id: 'placement-ros', name: 'Rest-of-search placement optimiser', desc: 'Auto-tune the rest-of-search placement multiplier from its own conversion performance.', category: 'Placement', trigger: 'SCHEDULE', params: [{ key: 'max', label: 'Max multiplier', kind: 'pct', default: 50 }], build: (p) => ({ conditions: [], actions: [{ type: 'set_placement_multiplier', placement: 'PLACEMENT_REST_OF_SEARCH', maxPct: N(p, 'max', 50) }, notify('Rest-of-search placement tuned')], maxExecutionsPerDay: 4 }) },

  // ── Inventory & promotions (distinct) ───────────────────────────────────
  { id: 'promo-aged-only', name: 'Clearance promo on aged stock', desc: 'Just launch a clearance promotion on stock nearing long-term storage (without pausing its ads).', category: 'Inventory & retail', trigger: 'FBA_AGE_THRESHOLD_REACHED', params: [pDays('days', 'Days to LTS ≤', 21), pPct('discount', 'Discount', 20)], build: (p) => ({ conditions: [{ field: 'fbaAge.daysToLtsThreshold', op: 'lte', value: N(p, 'days', 21) }], actions: [{ type: 'create_amazon_promotion', discountPct: N(p, 'discount', 20), durationDays: 14, reason: 'Aged-stock clearance' }, notify('Clearance promo created for aged stock')], maxExecutionsPerDay: 20 }) },

  // ── Cross-market & scheduled state (distinct) ───────────────────────────
  { id: 'target-acos-account', name: 'Account-wide target-ACOS reset', desc: 'On a schedule, reset every campaign’s target ACOS to a chosen value — a clean monthly recalibration.', category: 'Bidding', trigger: 'SCHEDULE', params: [{ key: 'target', label: 'Target ACOS', kind: 'pct', default: 30 }], build: (p) => ({ conditions: [], actions: [{ type: 'set_campaign_target_acos', targetAcos: N(p, 'target', 30) / 100, scope: 'all' }, notify('Account-wide target ACOS reset')], maxExecutionsPerDay: 1 }) },
  { id: 'resume-campaigns-schedule', name: 'Resume eligible paused campaigns', desc: 'On a schedule, resume campaigns that were auto-paused once their blocking condition (stock, budget) clears.', category: 'Inventory & retail', trigger: 'SCHEDULE', params: [], build: () => ({ conditions: [], actions: [{ type: 'resume_campaign', reason: 'Blocking condition cleared' }, notify('Eligible campaigns resumed')], maxExecutionsPerDay: 24 }) },

  // ── More distinct alerts (each a different signal) ──────────────────────
  { id: 'alert-low-ctr', name: 'Alert: low click-through rate', desc: 'Flag keywords/terms whose CTR is dragging — review for relevance or creative.', category: 'Alerts', trigger: 'KEYWORD_LOW_CTR', params: [], build: () => ({ conditions: [], actions: [alert('Low-CTR keyword detected')], maxExecutionsPerDay: 40 }) },
  { id: 'alert-no-impr', name: 'Alert: keyword getting no impressions', desc: 'Be told when a keyword is starved of impressions so you can decide whether to raise its bid.', category: 'Alerts', trigger: 'KEYWORD_ZERO_IMPRESSIONS', params: [], build: () => ({ conditions: [], actions: [alert('Keyword starved of impressions')], maxExecutionsPerDay: 30 }) },
  { id: 'alert-converting-term', name: 'Alert: converting search term to harvest', desc: 'Surface search terms that are converting so you can promote them (opportunity, not a problem).', category: 'Alerts', trigger: 'SEARCH_TERM_CONVERTING', params: [], build: () => ({ conditions: [], actions: [alert('Converting search term ready to harvest')], maxExecutionsPerDay: 12 }) },
  { id: 'alert-aged-stock', name: 'Alert: stock nearing long-term storage', desc: 'Notify you when a SKU is about to incur long-term-storage fees so you can plan a clearance.', category: 'Alerts', trigger: 'FBA_AGE_THRESHOLD_REACHED', params: [pDays('days', 'Days to LTS ≤', 30)], build: (p) => ({ conditions: [{ field: 'fbaAge.daysToLtsThreshold', op: 'lte', value: N(p, 'days', 30) }], actions: [alert('Stock nearing long-term storage')], maxExecutionsPerDay: 20 }) },
  { id: 'alert-target-underperform', name: 'Alert: underperforming target', desc: 'Flag any keyword/ASIN target spending past a limit with no sales — without auto-pausing it.', category: 'Alerts', trigger: 'AD_TARGET_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 20)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 20) * 100 }, { field: 'adTarget.salesCents', op: 'eq', value: 0 }], actions: [alert('Underperforming target detected')], maxExecutionsPerDay: 40 }) },

  // ── More distinct actions/scopes (different behaviour, not threshold twins) ──
  { id: 'pause-campaign-wasted', name: 'Pause campaign on heavy keyword waste', desc: 'When a keyword burns past a hard spend limit with zero sales, pause the whole campaign (decisive, not just the ad group).', category: 'Pruning', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 50)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 50) * 100 }], actions: [{ type: 'pause_campaign', reason: 'Heavy keyword waste' }, notify('Campaign paused — heavy keyword waste')], maxExecutionsPerDay: 20 }) },
  { id: 'negate-campaign-wide', name: 'Negate wasted term campaign-wide', desc: 'Block a wasteful search term across the entire campaign (not just one ad group) so it can never leak spend elsewhere in it.', category: 'Negation', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 15)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 15) * 100 }], actions: [{ type: 'add_negative_exact', scope: 'CAMPAIGN', reason: 'Wasted spend — campaign-wide' }, notify('Term negated campaign-wide')], maxExecutionsPerDay: 60 }) },
  { id: 'enable-scheduled-campaigns', name: 'Enable campaigns on schedule', desc: 'Turn specific campaigns back on at a scheduled time — e.g. seasonal or event campaigns that you switch on for a window.', category: 'Inventory & retail', trigger: 'SCHEDULE', params: [], build: () => ({ conditions: [], actions: [{ type: 'enable_campaign', reason: 'Scheduled enable' }, notify('Scheduled campaigns enabled')], maxExecutionsPerDay: 24 }) },
  { id: 'cap-budget-weak-acos', name: 'Cap daily budget on weak ACOS', desc: 'Pin a campaign to a low fixed daily budget (a hard cap) once its ACOS crosses your line — different from a relative trim.', category: 'Budget', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', params: [pPct('acos', 'ACOS ≥', 45), pEur('budget', 'Cap budget at (€/day)', 10)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 45) / 100 }], actions: [{ type: 'set_daily_budget', budgetEur: N(p, 'budget', 10), reason: 'Weak ACOS — hard cap' }, notify('Daily budget capped on weak ACOS')], maxExecutionsPerDay: 10 }) },
  { id: 'biddown-dead-target', name: 'Ease bids on underperforming targets', desc: 'Gently cut (not pause/floor) bids on targets spending without selling — a softer first response before harsher action.', category: 'Bidding', trigger: 'AD_TARGET_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 15), pStep(20)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 15) * 100 }, { field: 'adTarget.salesCents', op: 'eq', value: 0 }], actions: [{ type: 'bid_down', target: 'keyword', percent: N(p, 'step', 20), reason: 'Underperforming target' }, notify('Bids eased on underperforming targets')], maxExecutionsPerDay: 60 }) },
  { id: 'pause-adgroup-cvr', name: 'Pause ad group on CVR collapse', desc: 'Pause just the affected ad group (not the whole campaign) when its conversion rate collapses.', category: 'Conversion', trigger: 'CVR_DROP', params: [], build: () => ({ conditions: [], actions: [{ type: 'pause_ad_group', reason: 'CVR collapse' }, notify('Ad group paused — CVR collapse')], maxExecutionsPerDay: 20 }) },
  { id: 'target-acos-cvr', name: 'Tighten target ACOS on CVR drop', desc: 'Lower the campaign target ACOS when conversion rate drops, so the engine bids more conservatively until it recovers.', category: 'Conversion', trigger: 'CVR_DROP', params: [{ key: 'target', label: 'New target ACOS', kind: 'pct', default: 25 }], build: (p) => ({ conditions: [], actions: [{ type: 'set_campaign_target_acos', targetAcos: N(p, 'target', 25) / 100 }, notify('Target ACOS tightened — CVR drop')], maxExecutionsPerDay: 20 }) },

  // ══ Engine expansion (E-series) — net-new triggers ════════════════════
  // KEYWORD_HIGH_ACOS — keywords that convert but run inefficiently. Four
  // distinct intents on one signal (escalating response), not threshold twins.
  { id: 'biddown-kw-high-acos', name: 'Bid down high-ACOS keywords', desc: 'Trim the bid on individual keywords that convert but at an ACOS above your ceiling — protect margin without killing a converter.', category: 'Bidding', trigger: 'KEYWORD_HIGH_ACOS', params: [pAcos(40), pStep(20)], build: (p) => ({ conditions: [{ field: 'adTarget.acos', op: 'gte', value: N(p, 'acos', 40) / 100 }], actions: [{ type: 'bid_down', target: 'keyword', percent: N(p, 'step', 20), reason: 'High keyword ACOS' }, notify('Bids trimmed on high-ACOS keywords')], maxExecutionsPerDay: 80 }) },
  { id: 'floor-kw-high-acos', name: 'Floor egregiously inefficient keywords', desc: 'Drop the bid to the floor on keywords whose ACOS is far past your limit — keep them alive for data but stop the bleed.', category: 'Bidding', trigger: 'KEYWORD_HIGH_ACOS', params: [pAcos(90)], build: (p) => ({ conditions: [{ field: 'adTarget.acos', op: 'gte', value: N(p, 'acos', 90) / 100 }], actions: [{ type: 'lower_bid_to_floor', reason: 'Egregious keyword ACOS' }, notify('Inefficient keywords floored')], maxExecutionsPerDay: 60 }) },
  { id: 'archive-kw-high-acos', name: 'Archive chronically inefficient keywords', desc: 'Retire keywords that keep converting far above your ACOS ceiling and past a spend threshold — they drain the budget.', category: 'Pruning', trigger: 'KEYWORD_HIGH_ACOS', params: [pAcos(100), pEur('minSpend', 'Spend ≥', 20)], build: (p) => ({ conditions: [{ field: 'adTarget.acos', op: 'gte', value: N(p, 'acos', 100) / 100 }, { field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 20) * 100 }], actions: [{ type: 'archive_keyword', reason: 'Chronically inefficient' }, notify('Inefficient keyword archived')], maxExecutionsPerDay: 40 }) },
  { id: 'alert-kw-high-acos', name: 'Alert: keyword ACOS over ceiling', desc: 'Notify you when a converting keyword crosses your ACOS ceiling — decide the fix yourself.', category: 'Alerts', trigger: 'KEYWORD_HIGH_ACOS', params: [pAcos(50)], build: (p) => ({ conditions: [{ field: 'adTarget.acos', op: 'gte', value: N(p, 'acos', 50) / 100 }], actions: [{ type: 'alert_operator', message: 'Keyword ACOS over ceiling' }], maxExecutionsPerDay: 100 }) },
  // KEYWORD_SCALE_OPPORTUNITY — proven winners with headroom to grow.
  { id: 'scale-kw-winners', name: 'Scale bids on winning keywords', desc: 'Raise the bid on individual keywords clearing a ROAS bar with real orders, to win more of a profitable term.', category: 'Bidding', trigger: 'KEYWORD_SCALE_OPPORTUNITY', params: [pRoas('roas', 'ROAS ≥', 4), { key: 'minOrders', label: 'Orders ≥', kind: 'num', default: 2 }, pStep(15)], build: (p) => ({ conditions: [{ field: 'adTarget.roas', op: 'gte', value: N(p, 'roas', 4) }, { field: 'adTarget.orders', op: 'gte', value: N(p, 'minOrders', 2) }], actions: [{ type: 'bid_up', target: 'keyword', percent: N(p, 'step', 15), reason: 'Scaling a proven winner' }, notify('Bids raised on winning keywords')], maxExecutionsPerDay: 60, maxDailyAdSpendCentsEur: 20000 }) },
  { id: 'alert-scale-opp', name: 'Alert: keyword ready to scale', desc: 'Surface high-ROAS keywords with headroom so you can scale them by hand.', category: 'Alerts', trigger: 'KEYWORD_SCALE_OPPORTUNITY', params: [pRoas('roas', 'ROAS ≥', 5)], build: (p) => ({ conditions: [{ field: 'adTarget.roas', op: 'gte', value: N(p, 'roas', 5) }], actions: [{ type: 'alert_operator', message: 'Keyword ready to scale' }], maxExecutionsPerDay: 100 }) },
  // AD_GROUP_UNDERPERFORMING — manage at the ad-group level.
  { id: 'pause-adgroup-underperf', name: 'Pause underperforming ad groups', desc: 'Pause an entire ad group that has spent past your limit with no sales — broader than per-keyword pruning.', category: 'Bidding', trigger: 'AD_GROUP_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 10)], build: (p) => ({ conditions: [{ field: 'adGroup.spendCents', op: 'gte', value: N(p, 'minSpend', 10) * 100 }, { field: 'adGroup.salesCents', op: 'eq', value: 0 }], actions: [{ type: 'pause_ad_group', reason: 'Ad group spent with no sales' }, notify('Underperforming ad group paused')], maxExecutionsPerDay: 30 }) },
  { id: 'biddown-adgroup-underperf', name: 'Bid down weak ad groups', desc: 'Cut every bid in an ad group whose ACOS has drifted past your ceiling — rein in the whole group at once.', category: 'Bidding', trigger: 'AD_GROUP_UNDERPERFORMING', params: [pAcos(50), pStep(20)], build: (p) => ({ conditions: [{ field: 'adGroup.acos', op: 'gte', value: N(p, 'acos', 50) / 100 }], actions: [{ type: 'bid_down', target: 'ad_group', percent: N(p, 'step', 20), reason: 'Weak ad group ACOS' }, notify('Bids cut across a weak ad group')], maxExecutionsPerDay: 40 }) },
  { id: 'alert-adgroup-underperf', name: 'Alert: ad group underperforming', desc: 'Notify you when an ad group crosses your spend-with-no-sales line.', category: 'Alerts', trigger: 'AD_GROUP_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 10)], build: (p) => ({ conditions: [{ field: 'adGroup.spendCents', op: 'gte', value: N(p, 'minSpend', 10) * 100 }, { field: 'adGroup.salesCents', op: 'eq', value: 0 }], actions: [{ type: 'alert_operator', message: 'Ad group underperforming' }], maxExecutionsPerDay: 50 }) },
  // NEW_TO_BRAND_WINNER — scale genuine brand growth (new-to-brand customers).
  { id: 'scale-ntb-winners', name: 'Scale budget on new-to-brand winners', desc: 'Raise the daily budget on campaigns bringing in new-to-brand customers — invest in genuine brand growth, not just repeat buyers.', category: 'Budget', trigger: 'NEW_TO_BRAND_WINNER', params: [{ key: 'minNtb', label: 'New-to-brand orders ≥', kind: 'num', default: 2 }, pStep(20)], build: (p) => ({ conditions: [{ field: 'campaign.ntbOrders', op: 'gte', value: N(p, 'minNtb', 2) }], actions: [{ type: 'adjust_ad_budget', percent: N(p, 'step', 20), reason: 'New-to-brand winner' }, notify('Budget scaled on a new-to-brand winner')], maxExecutionsPerDay: 10, maxDailyAdSpendCentsEur: 20000 }) },
  { id: 'alert-ntb-winner', name: 'Alert: new-to-brand winner', desc: 'Surface campaigns acquiring new-to-brand customers so you can double down deliberately.', category: 'Alerts', trigger: 'NEW_TO_BRAND_WINNER', params: [{ key: 'minNtb', label: 'New-to-brand orders ≥', kind: 'num', default: 3 }], build: (p) => ({ conditions: [{ field: 'campaign.ntbOrders', op: 'gte', value: N(p, 'minNtb', 3) }], actions: [{ type: 'alert_operator', message: 'New-to-brand winner — consider scaling' }], maxExecutionsPerDay: 50 }) },
  // CAMPAIGN_NO_SALES — dead spend at the campaign level.
  { id: 'pause-dead-campaign', name: 'Pause campaigns with no sales', desc: 'Hard-stop a campaign that has spent past your limit over 30 days with zero attributed sales — stop pure dead spend.', category: 'Bidding', trigger: 'CAMPAIGN_NO_SALES', params: [pEur('minSpend', 'Spend ≥', 15)], build: (p) => ({ conditions: [{ field: 'campaign.spendCents', op: 'gte', value: N(p, 'minSpend', 15) * 100 }], actions: [{ type: 'pause_campaign', reason: 'No sales over 30 days' }, notify('Campaign paused — no sales')], maxExecutionsPerDay: 10 }) },
  { id: 'alert-dead-campaign', name: 'Alert: campaign spending with no sales', desc: 'Notify you when a campaign racks up spend over 30 days without a single sale — investigate before pausing.', category: 'Alerts', trigger: 'CAMPAIGN_NO_SALES', params: [pEur('minSpend', 'Spend ≥', 10)], build: (p) => ({ conditions: [{ field: 'campaign.spendCents', op: 'gte', value: N(p, 'minSpend', 10) * 100 }], actions: [{ type: 'alert_operator', message: 'Campaign spending with no sales' }], maxExecutionsPerDay: 50 }) },
]
