/**
 * Distinct automation registry. Each entry is ONE automation concept with its
 * own parameter schema — configured per use (not shipped as fixed threshold
 * twins). build(params) emits a real {conditions, actions} spec against the live
 * engine vocabulary (triggers + ~24 action handlers + condition fields), so every
 * automation executes. The configurator renders params; the builder covers the
 * rest for unlimited custom rules.
 */

import { MORE_AUTOMATIONS } from './automations.more'

export type ParamKind = 'pct' | 'eur' | 'num' | 'days' | 'roas' | 'select'
export interface ParamDef { key: string; label: string; kind: ParamKind; default: number | string; options?: Array<{ v: string; l: string }>; hint?: string }
export interface BuiltRule { conditions: Array<{ field: string; op: string; value: number }>; actions: Array<Record<string, unknown>>; maxExecutionsPerDay?: number; maxDailyAdSpendCentsEur?: number | null }
export interface AutomationDef {
  id: string; name: string; desc: string; category: string; trigger: string
  marquee?: boolean
  params: ParamDef[]
  build: (p: Record<string, number | string>) => BuiltRule
}

const N = (p: Record<string, number | string>, k: string, d = 0) => { const v = Number(p[k]); return Number.isFinite(v) ? v : d }
const _S = (p: Record<string, number | string>, k: string, d = '') => (p[k] != null ? String(p[k]) : d); void _S
const notify = (message: string) => ({ type: 'notify', target: 'operator', message })
// param presets
const pPct = (key: string, label: string, def: number, hint?: string): ParamDef => ({ key, label, kind: 'pct', default: def, hint })
const pEur = (key: string, label: string, def: number, hint?: string): ParamDef => ({ key, label, kind: 'eur', default: def, hint })
const pNum = (key: string, label: string, def: number, hint?: string): ParamDef => ({ key, label, kind: 'num', default: def, hint })
const pDays = (key: string, label: string, def: number): ParamDef => ({ key, label, kind: 'days', default: def })
const pRoas = (key: string, label: string, def: number): ParamDef => ({ key, label, kind: 'roas', default: def })
const pAcos = (def: number): ParamDef => ({ key: 'acos', label: 'ACOS threshold', kind: 'pct', default: def })
const pStep = (def: number): ParamDef => ({ key: 'step', label: 'Adjust by', kind: 'pct', default: def })

const BASE_AUTOMATIONS: AutomationDef[] = [
  // ── Bidding ───────────────────────────────────────────────────────────
  { id: 'cut-bids-acos', name: 'Cut bids on high ACOS', desc: 'Lower the ad-group bid when a campaign’s ACOS climbs above your threshold — defend margin on keywords turning unprofitable.', category: 'Bidding', trigger: 'CAC_SPIKE', marquee: true, params: [pAcos(40), pStep(20)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 40) / 100 }], actions: [{ type: 'bid_down', target: 'ad_group', percent: N(p, 'step', 20) }, notify('Bids cut on ACOS spike')], maxExecutionsPerDay: 50 }) },
  { id: 'raise-bids-winners', name: 'Raise bids on winners', desc: 'Push bids up on campaigns beating a ROAS target so your best performers win more impressions.', category: 'Bidding', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', marquee: true, params: [pRoas('roas', 'ROAS at or above', 4), pStep(15)], build: (p) => ({ conditions: [{ field: 'campaign.roas', op: 'gte', value: N(p, 'roas', 4) }], actions: [{ type: 'bid_up', target: 'ad_group', percent: N(p, 'step', 15) }, notify('Bids raised on a ROAS winner')], maxExecutionsPerDay: 30, maxDailyAdSpendCentsEur: 20000 }) },
  { id: 'floor-wasted-kw', name: 'Drop wasted keywords to bid floor', desc: 'When a keyword burns spend without sales, cut its bid to the floor (€0.05) instead of pausing — keep presence, kill the bleed.', category: 'Bidding', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 15)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 15) * 100 }], actions: [{ type: 'lower_bid_to_floor', reason: 'Wasted spend — bid to floor' }, notify('Keyword dropped to bid floor')], maxExecutionsPerDay: 80 }) },
  { id: 'boost-no-impressions', name: 'Boost starved keywords', desc: 'Raise bids on keywords getting (almost) no impressions so they actually enter the auction.', category: 'Bidding', trigger: 'KEYWORD_ZERO_IMPRESSIONS', params: [pStep(25)], build: (p) => ({ conditions: [], actions: [{ type: 'bid_up', target: 'keyword', percent: N(p, 'step', 25) }, notify('Starved keywords boosted')], maxExecutionsPerDay: 60 }) },
  { id: 'rank-defense', name: 'Defend organic rank', desc: 'Raise bids on your priority keywords to protect ranking and Buy Box share against competitors.', category: 'Bidding', trigger: 'SCHEDULE', params: [pStep(15)], build: (p) => ({ conditions: [], actions: [{ type: 'raise_bids_for_rank_defense', percent: N(p, 'step', 15) }, notify('Rank-defense bids applied')], maxExecutionsPerDay: 4 }) },
  { id: 'price-change-bids', name: 'Re-bid on price changes', desc: 'Automatically scale bids when your product price changes so target ACOS stays consistent with the new margin.', category: 'Bidding', trigger: 'SCHEDULE', params: [], build: () => ({ conditions: [], actions: [{ type: 'scale_bids_for_price_change' }, notify('Bids re-scaled for price changes')], maxExecutionsPerDay: 6 }) },
  { id: 'profit-bid-opt', name: 'Profit-native bid optimisation', desc: 'Daily: nudge every keyword bid toward each product’s true-profit ACOS target with Bayesian smoothing for low-data keywords.', category: 'Bidding', trigger: 'SCHEDULE', marquee: true, params: [], build: () => ({ conditions: [], actions: [{ type: 'bid_to_target_acos', profitMode: true, bayesian: true, acosMode: 'profit' }, notify('Profit bid optimisation ran')], maxExecutionsPerDay: 2 }) },
  { id: 'target-acos-bid-opt', name: 'Target-ACOS bid optimisation', desc: 'Daily bid tuning toward a fixed ACOS goal (revenue-led rather than margin-led).', category: 'Bidding', trigger: 'SCHEDULE', params: [pAcos(30)], build: (p) => ({ conditions: [], actions: [{ type: 'bid_to_target_acos', profitMode: false, bayesian: true, acosMode: 'fixed', targetAcos: N(p, 'acos', 30) / 100 }, notify('Target-ACOS bid optimisation ran')], maxExecutionsPerDay: 2 }) },
  { id: 'set-target-acos', name: 'Set campaign target ACOS on drift', desc: 'When a campaign drifts over your ACOS ceiling, set its campaign-level target ACOS so the engine reins it in.', category: 'Bidding', trigger: 'CAC_SPIKE', params: [pAcos(45), { key: 'target', label: 'New target ACOS', kind: 'pct', default: 30 }], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 45) / 100 }], actions: [{ type: 'set_campaign_target_acos', targetAcos: N(p, 'target', 30) / 100 }, notify('Target ACOS reset on a drifting campaign')], maxExecutionsPerDay: 20 }) },

  // ── Harvesting & negation ───────────────────────────────────────────────
  { id: 'harvest-negate', name: 'Harvest & negate search terms', desc: 'Promote converting search terms to exact-match keywords and negate wasteful ones — the core search-term automation.', category: 'Harvesting', trigger: 'SCHEDULE', marquee: true, params: [pDays('window', 'Look-back window', 60), pNum('minOrders', 'Promote at orders ≥', 2), pEur('minSpend', 'Negate at wasted spend ≥', 10)], build: (p) => ({ conditions: [], actions: [{ type: 'harvest_and_negate', windowDays: N(p, 'window', 60), minOrders: N(p, 'minOrders', 2), minSpendCents: N(p, 'minSpend', 10) * 100, graduationBidEur: 0.5 }, notify('Harvest & negate ran')], maxExecutionsPerDay: 3 }) },
  { id: 'promote-converting', name: 'Promote converting search terms', desc: 'Graduate auto/broad search terms that are converting into their own exact-match keywords to lock in cheaper, controlled traffic.', category: 'Harvesting', trigger: 'SEARCH_TERM_CONVERTING', params: [pNum('minOrders', 'Orders ≥', 2), pEur('bid', 'Starting bid (€)', 0.5)], build: (p) => ({ conditions: [], actions: [{ type: 'promote_to_exact', minOrders: N(p, 'minOrders', 2), bidEur: N(p, 'bid', 0.5) }, notify('Converting terms promoted to exact')], maxExecutionsPerDay: 6 }) },
  { id: 'negate-wasted-term', name: 'Negate wasted search terms', desc: 'Add zero-converting, spend-burning search terms as negative-exact so you stop paying for them.', category: 'Negation', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 10)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 10) * 100 }], actions: [{ type: 'add_negative_exact', reason: 'Wasted spend' }, notify('Wasted term negated')], maxExecutionsPerDay: 80 }) },
  { id: 'negate-low-ctr', name: 'Negate chronically low-CTR terms', desc: 'Negate search terms whose click-through rate is so low they drag relevance and waste impressions.', category: 'Negation', trigger: 'KEYWORD_LOW_CTR', params: [pPct('ctr', 'CTR below', 0.2)], build: (_p) => ({ conditions: [], actions: [{ type: 'add_negative_exact', reason: 'Chronically low CTR' }, notify('Low-CTR term negated')], maxExecutionsPerDay: 60 }) },
  { id: 'sync-negatives', name: 'Sync negatives across campaigns', desc: 'Propagate every negative keyword to all relevant campaigns so a term you killed in one place can’t leak spend elsewhere.', category: 'Negation', trigger: 'SCHEDULE', params: [], build: () => ({ conditions: [], actions: [{ type: 'sync_negatives_across_campaigns' }, notify('Negatives synced across campaigns')], maxExecutionsPerDay: 4 }) },

  // ── Pruning (keyword/target lifecycle) ─────────────────────────────────
  { id: 'archive-wasted-kw', name: 'Archive wasted keywords', desc: 'Permanently archive keywords that spent without ever selling — clean the account, not just pause.', category: 'Pruning', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 25)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 25) * 100 }], actions: [{ type: 'archive_keyword', reason: 'Wasted spend' }, notify('Wasted keyword archived')], maxExecutionsPerDay: 50 }) },
  { id: 'archive-zero-impr', name: 'Archive dead (zero-impression) keywords', desc: 'Archive keywords that have had no impressions for ages — they’re inert clutter.', category: 'Pruning', trigger: 'KEYWORD_ZERO_IMPRESSIONS', params: [], build: () => ({ conditions: [], actions: [{ type: 'archive_keyword', reason: 'No impressions' }, notify('Dead keyword archived')], maxExecutionsPerDay: 60 }) },
  { id: 'pause-wasted-adgroup', name: 'Pause ad group on dead target', desc: 'When a target spends past your limit with zero sales, pause its ad group (coarse but decisive).', category: 'Pruning', trigger: 'AD_TARGET_UNDERPERFORMING', params: [pEur('minSpend', 'Spend ≥', 20)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 20) * 100 }, { field: 'adTarget.salesCents', op: 'eq', value: 0 }], actions: [{ type: 'pause_ad_group', reason: 'Dead target' }, notify('Ad group paused — dead target')], maxExecutionsPerDay: 50 }) },

  // ── Budget ─────────────────────────────────────────────────────────────
  { id: 'scale-budget-winners', name: 'Scale budget on capped winners', desc: 'Raise the daily budget on campaigns with strong ROAS that are hitting their cap — stop leaving sales on the table.', category: 'Budget', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', marquee: true, params: [pRoas('roas', 'ROAS ≥', 4), pPct('util', 'Budget used ≥', 85), pStep(20)], build: (p) => ({ conditions: [{ field: 'campaign.roas', op: 'gte', value: N(p, 'roas', 4) }, { field: 'campaign.budgetUtilization', op: 'gte', value: N(p, 'util', 85) / 100 }], actions: [{ type: 'adjust_ad_budget', percent: N(p, 'step', 20), reason: 'Capped winner' }, notify('Budget scaled on a capped winner')], maxExecutionsPerDay: 10, maxDailyAdSpendCentsEur: 20000 }) },
  { id: 'trim-budget-losers', name: 'Trim budget on weak ACOS', desc: 'Reduce the daily budget on campaigns whose ACOS has drifted over your ceiling — slow the bleed without pausing.', category: 'Budget', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', params: [pAcos(40), pStep(15)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 40) / 100 }, { field: 'campaign.spendCents', op: 'gte', value: 5000 }], actions: [{ type: 'adjust_ad_budget', percent: -N(p, 'step', 15), reason: 'Weak ACOS' }, notify('Budget trimmed on weak ACOS')], maxExecutionsPerDay: 10 }) },
  { id: 'set-daily-budget', name: 'Set a fixed daily budget on drift', desc: 'Pin a campaign’s daily budget to an exact amount when it exceeds your ACOS ceiling.', category: 'Budget', trigger: 'CAMPAIGN_PERFORMANCE_BUDGET', params: [pAcos(50), pEur('budget', 'Set budget to (€/day)', 20)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 50) / 100 }], actions: [{ type: 'set_daily_budget', budgetEur: N(p, 'budget', 20), reason: 'ACOS ceiling hit' }, notify('Daily budget pinned')], maxExecutionsPerDay: 10 }) },
  { id: 'monthly-cap', name: 'Monthly spend cap (pause everything)', desc: 'When month-to-date spend hits your cap, pause every campaign — a guaranteed never-overspend failsafe.', category: 'Budget', trigger: 'SCHEDULE', marquee: true, params: [pEur('cap', 'Monthly cap (€)', 2000)], build: (p) => ({ conditions: [{ field: 'budget.monthlySpendCents', op: 'gte', value: N(p, 'cap', 2000) * 100 }], actions: [{ type: 'pause_all_campaigns', reason: 'Monthly cap reached' }, notify('Monthly cap hit — all campaigns paused')], maxExecutionsPerDay: 96 }) },
  { id: 'reroute-budget', name: 'Reroute budget to best marketplace', desc: 'Shift budget toward the marketplaces delivering the best return, away from the laggards.', category: 'Budget', trigger: 'SCHEDULE', params: [], build: () => ({ conditions: [], actions: [{ type: 'reroute_marketplace_budget' }, notify('Budget rerouted to best marketplaces')], maxExecutionsPerDay: 2 }) },

  // ── Profitability ───────────────────────────────────────────────────────
  { id: 'pause-profit-breach', name: 'Pause campaign on profit breach', desc: 'Pause a campaign whose ad spend exceeds the true profit of the products it advertises.', category: 'Profitability', trigger: 'AD_SPEND_PROFITABILITY_BREACH', params: [], build: () => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'pause_campaign', reason: 'Ad spend exceeded true profit' }, notify('Campaign paused — margin-negative')], maxExecutionsPerDay: 20 }) },
  { id: 'biddown-profit-breach', name: 'Bid down on profit breach', desc: 'Instead of pausing, pull bids back when a campaign turns margin-negative to nurse it toward profitability.', category: 'Profitability', trigger: 'AD_SPEND_PROFITABILITY_BREACH', params: [pStep(20)], build: (p) => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'bid_down', target: 'ad_group', percent: N(p, 'step', 20), reason: 'Margin-negative' }, notify('Bids cut — margin-negative')], maxExecutionsPerDay: 20 }) },
  { id: 'target-acos-profit-breach', name: 'Tighten target ACOS on profit breach', desc: 'Lower a campaign’s target ACOS automatically when it stops paying, so the engine bids more conservatively.', category: 'Profitability', trigger: 'AD_SPEND_PROFITABILITY_BREACH', params: [{ key: 'target', label: 'New target ACOS', kind: 'pct', default: 20 }], build: (p) => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'set_campaign_target_acos', targetAcos: N(p, 'target', 20) / 100 }, notify('Target ACOS tightened — margin-negative')], maxExecutionsPerDay: 20 }) },

  // ── Conversion (CVR) ────────────────────────────────────────────────────
  { id: 'pause-cvr-drop', name: 'Pause campaign on conversion-rate collapse', desc: 'Pause a campaign when its conversion rate falls off a cliff — usually a listing, price, or stock problem.', category: 'Conversion', trigger: 'CVR_DROP', params: [], build: () => ({ conditions: [], actions: [{ type: 'pause_campaign', reason: 'CVR collapsed' }, notify('Campaign paused — CVR collapsed')], maxExecutionsPerDay: 20 }) },
  { id: 'biddown-cvr-drop', name: 'Bid down on conversion-rate drop', desc: 'Ease off bids when conversion rate drops so you spend less while the underlying issue is fixed.', category: 'Conversion', trigger: 'CVR_DROP', params: [pStep(25)], build: (p) => ({ conditions: [], actions: [{ type: 'bid_down', target: 'ad_group', percent: N(p, 'step', 25), reason: 'CVR drop' }, notify('Bids eased — CVR drop')], maxExecutionsPerDay: 20 }) },

  // ── Placement ───────────────────────────────────────────────────────────
  { id: 'placement-tos', name: 'Top-of-search placement optimiser', desc: 'Auto-tune the top-of-search placement multiplier based on how that placement converts vs the rest.', category: 'Placement', trigger: 'SCHEDULE', params: [{ key: 'max', label: 'Max multiplier', kind: 'pct', default: 100 }], build: (p) => ({ conditions: [], actions: [{ type: 'set_placement_multiplier', placement: 'PLACEMENT_TOP', maxPct: N(p, 'max', 100) }, notify('Top-of-search placement tuned')], maxExecutionsPerDay: 4 }) },
  { id: 'placement-pdp', name: 'Product-page placement optimiser', desc: 'Auto-tune the product-pages placement multiplier from its own conversion performance.', category: 'Placement', trigger: 'SCHEDULE', params: [{ key: 'max', label: 'Max multiplier', kind: 'pct', default: 80 }], build: (p) => ({ conditions: [], actions: [{ type: 'set_placement_multiplier', placement: 'PLACEMENT_PRODUCT_PAGE', maxPct: N(p, 'max', 80) }, notify('Product-page placement tuned')], maxExecutionsPerDay: 4 }) },

  // ── Inventory & retail ──────────────────────────────────────────────────
  { id: 'retail-guard', name: 'Retail guard (stock & Buy Box)', desc: 'Every 15 min: pause ads on out-of-stock or lost-Buy-Box products and resume them when sellable again.', category: 'Inventory & retail', trigger: 'SCHEDULE', marquee: true, params: [], build: () => ({ conditions: [], actions: [{ type: 'retail_guard' }, notify('Retail guard adjusted campaigns')], maxExecutionsPerDay: 96 }) },
  { id: 'liquidate-aged', name: 'Liquidate aged stock', desc: 'When a SKU nears long-term-storage, pause its fresh-product ads and launch a clearance promo.', category: 'Inventory & retail', trigger: 'FBA_AGE_THRESHOLD_REACHED', params: [pDays('days', 'Days to LTS ≤', 14), pPct('discount', 'Promo discount', 15)], build: (p) => ({ conditions: [{ field: 'fbaAge.daysToLtsThreshold', op: 'lte', value: N(p, 'days', 14) }], actions: [{ type: 'liquidate_aged_stock', discountPct: N(p, 'discount', 15) }, notify('Aged-stock liquidation fired')], maxExecutionsPerDay: 20 }) },
  { id: 'pause-aged-ads', name: 'Pause ads on aged stock', desc: 'Just stop advertising fresh units of a product whose stock is about to go long-term (no promo).', category: 'Inventory & retail', trigger: 'FBA_AGE_THRESHOLD_REACHED', params: [pDays('days', 'Days to LTS ≤', 14)], build: (p) => ({ conditions: [{ field: 'fbaAge.daysToLtsThreshold', op: 'lte', value: N(p, 'days', 14) }], actions: [{ type: 'pause_ad_group', reason: 'Aged stock' }, notify('Ads paused on aged stock')], maxExecutionsPerDay: 20 }) },

  // ── Alerts (notify-only intelligence) ──────────────────────────────────
  { id: 'alert-acos-spike', name: 'Alert: ACOS spike', desc: 'Get notified the moment a campaign’s ACOS crosses your line — decide the fix yourself.', category: 'Alerts', trigger: 'CAC_SPIKE', params: [pAcos(50)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 50) / 100 }], actions: [{ type: 'alert_operator', message: 'ACOS spike detected' }], maxExecutionsPerDay: 50 }) },
  { id: 'alert-profit-breach', name: 'Alert: ad spend beat true profit', desc: 'Notify-only flag when a campaign’s 30-day spend exceeds the true profit of its products.', category: 'Alerts', trigger: 'AD_SPEND_PROFITABILITY_BREACH', marquee: true, params: [], build: () => ({ conditions: [{ field: 'profit.netCents', op: 'lt', value: 0 }], actions: [{ type: 'alert_operator', message: 'Ad spend > true profit (30d)' }], maxExecutionsPerDay: 10 }) },
  { id: 'alert-cvr-drop', name: 'Alert: conversion-rate drop', desc: 'Be told when a campaign’s conversion rate drops sharply, so you can check the listing/price/stock.', category: 'Alerts', trigger: 'CVR_DROP', params: [], build: () => ({ conditions: [], actions: [{ type: 'alert_operator', message: 'Conversion-rate drop detected' }], maxExecutionsPerDay: 30 }) },
  { id: 'alert-wasted-kw', name: 'Alert: wasted-spend keyword', desc: 'Flag keywords burning money with no sales, without touching them automatically.', category: 'Alerts', trigger: 'KEYWORD_WASTED_SPEND', params: [pEur('minSpend', 'Wasted spend ≥', 20)], build: (p) => ({ conditions: [{ field: 'adTarget.spendCents', op: 'gte', value: N(p, 'minSpend', 20) * 100 }], actions: [{ type: 'alert_operator', message: 'Wasted-spend keyword detected' }], maxExecutionsPerDay: 50 }) },

  // ── Campaign state ──────────────────────────────────────────────────────
  { id: 'pause-campaign-acos', name: 'Pause campaign on extreme ACOS', desc: 'Hard-stop an entire campaign once ACOS blows past a red-line threshold.', category: 'Bidding', trigger: 'CAC_SPIKE', params: [pAcos(100)], build: (p) => ({ conditions: [{ field: 'campaign.acos', op: 'gte', value: N(p, 'acos', 100) / 100 }], actions: [{ type: 'pause_campaign', reason: 'Extreme ACOS' }, notify('Campaign paused — extreme ACOS')], maxExecutionsPerDay: 20 }) },
]

// merge the base set with the additional distinct concepts (de-duped by id)
const MERGED = [...BASE_AUTOMATIONS, ...MORE_AUTOMATIONS]
const _seen = new Set<string>()
export const AUTOMATIONS: AutomationDef[] = MERGED.filter((a) => (_seen.has(a.id) ? false : (_seen.add(a.id), true)))
export const CATEGORIES = ['All', ...Array.from(new Set(AUTOMATIONS.map((a) => a.category)))]
export const AUTOMATION_COUNT = AUTOMATIONS.length
export const META_BY_ID: Record<string, AutomationDef> = Object.fromEntries(AUTOMATIONS.map((a) => [a.id, a]))

/** Build the conditions/actions for an automation given its (possibly default) params. */
export function buildRule(def: AutomationDef, params?: Record<string, number | string>): BuiltRule {
  const merged: Record<string, number | string> = {}
  for (const p of def.params) merged[p.key] = p.default
  if (params) Object.assign(merged, params)
  return def.build(merged)
}
