import { chromium } from '@playwright/test'
const B = 'http://localhost:3001/marketing/ads/rules-automation'
const b = await chromium.launch(); const p = await b.newPage()
const errors = []; p.on('pageerror', (e) => errors.push(String(e)))
const say = (m) => console.log(`[negp] ${m}`)

await p.goto(`${B}/negative-targeting`, { waitUntil: 'networkidle', timeout: 60000 })
const strip = await p.locator('.h10-hv-cohortline').textContent().catch(() => null)
say(`strip: ${strip ?? 'ABSENT'}`)

await p.goto(`${B}/builder/negative-targeting`, { waitUntil: 'networkidle', timeout: 60000 })
const note = await p.locator('.h10-pc-winnote').first().textContent()
say(`floor note: ${note?.includes('5 clicks') && note?.includes('€3')}`)
const condRows = await p.locator('.h10-rb-conds .cond:not(.then)').count()
const vals = await p.locator('.h10-rb-conds .cond input[aria-label="Value"]').all()
const v = []; for (const x of vals) v.push(await x.inputValue())
say(`default criteria rows: ${condRows} values=[${v.join(',')}] (expect Sales=0 AND Clicks>=5)`)
await p.click('.h10-rb-tmpl')
await p.waitForSelector('.h10-rb-tmpl-modal')
const starters = await p.locator('.h10-rb-tmpl-modal .tmrow .tmn').allTextContents()
say(`negative starters: ${starters.length} — ${starters.map((s) => s.split('Zero')[0].trim()).join(' · ')}`)
await p.locator('.h10-rb-tmpl-modal .tmrow button').nth(2).click() // Click sink → Sales=0 + Clicks>=20
await p.waitForTimeout(300)
const v2els = await p.locator('.h10-rb-conds .cond input[aria-label="Value"]').all()
const v2 = []; for (const x of v2els) v2.push(await x.inputValue())
say(`after starter 3: values=[${v2.join(',')}]`)
const dedupe = await p.locator('.h10-rb-dedupe').first().textContent()
say(`dedupe copy is negative-aware: ${dedupe?.includes('re-negate')}`)
const lvl = await p.locator('text=/campaign-level negatives have historically never confirmed/').count()
say(`negation-level landing-rate sentence: ${lvl === 1}`)
const saveT = await p.locator('button:has-text("Save Template")').count()
say(`Save Template offered for negative: ${saveT >= 1}`)
say(`pageerrors: ${errors.length}`)
await b.close()
