import { afterEach, expect, it, vi } from 'vitest'
const state = vi.hoisted(() => ({ workspace: 'one', seller: vi.fn(), client: vi.fn(), download: vi.fn(), api: vi.fn() }))
vi.mock('../../lib/workspace-context.js', () => ({ workspaceIdForQuery: () => state.workspace, workspaceContext: () => ({ workspaceId: state.workspace }) }))
vi.mock('../../lib/amazon-sp-client.js', () => ({ getAmazonSellerId: state.seller, getAmazonSpClient: state.client }))
vi.mock('./schema-document.js', () => ({ downloadAmazonSchema: state.download, schemaFingerprint: () => 'checked-schema' }))
import { amazonSellerSpec } from './seller-schema.service.js'
afterEach(() => vi.useRealTimers())
it('isolates seller and workspace requirements, refreshes stale schemas, and evicts failed requests', async () => {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-11'))
  state.seller.mockImplementation(async account => `seller-${account}`)
  state.client.mockResolvedValue({ callAPI: state.api })
  state.api.mockResolvedValue({ schema: { link: { resource: 'https://schema.example/document' } }, requirementsEnforced: 'ENFORCED' })
  state.download.mockResolvedValue({ type: 'object', properties: { item_name: { type: 'array', items: { type: 'object', properties: { value: { type: 'string' } } } } } })
  const first = await amazonSellerSpec('a', 'IT', 'JACKET')
  expect(await amazonSellerSpec('a', 'IT', 'JACKET')).toBe(first)
  await amazonSellerSpec('b', 'IT', 'JACKET')
  state.workspace = 'two'; await amazonSellerSpec('a', 'IT', 'JACKET')
  expect(state.api).toHaveBeenCalledTimes(3)
  expect(state.api).toHaveBeenNthCalledWith(2, expect.objectContaining({ query: expect.objectContaining({ sellerId: 'seller-b', requirementsEnforced: 'ENFORCED', marketplaceIds: ['APJ6JRA9NG5V4'] }) }))
  expect(state.api.mock.calls[0][0].query.parentage).toBeUndefined()
  await amazonSellerSpec('a', 'IT', 'JACKET', true)
  vi.advanceTimersByTime(16 * 60_000); await amazonSellerSpec('a', 'IT', 'JACKET')
  expect(state.api).toHaveBeenCalledTimes(5)
  state.api.mockRejectedValueOnce(new Error('Unavailable'))
  await expect(amazonSellerSpec('a', 'DE', 'JACKET')).rejects.toThrow('Unavailable')
  await expect(amazonSellerSpec('a', 'DE', 'JACKET')).resolves.toMatchObject({ schemaVersion: 'checked-schema' })
})
