// EC.2 — Field Source System types.
//
// Per-field state machine that lets operators choose where each
// listing field's value comes from (manual entry, master product,
// translations tab, AI suggestion, sibling marketplace, default),
// lock fields against re-resolve, and undo recent changes.
//
// Storage: hydrated from + persisted to localStorage during EC.2 so
// the system is fully testable without an API endpoint. EC.10 hoists
// the same shape into ChannelListing.platformAttributes._fieldSources
// via the DSP-series Save All flow — no consumer-side changes when
// that swap happens.

export type FieldSource =
  | 'manual'        // operator typed it directly on the listing
  | 'master'        // inherited from the product master record
  | 'translations'  // pulled from LocalesTab for this marketplace
  | 'ai'            // AI-suggested (list-wizard / cockpit assistant)
  | 'sibling'       // copied from another marketplace listing
  | 'default'       // no value set / fall back to system default

export interface HistoryEntry {
  source: FieldSource
  value: string
  timestamp: string  // ISO
}

export interface FieldSourceState {
  source: FieldSource
  value: string
  /** When true, a "re-resolve from source" never overwrites this value
   *  even if the upstream (e.g. master.name) changes. The lock applies
   *  to the SOURCE, not to the value — a locked field is still
   *  editable when source === 'manual'. */
  locked: boolean
  history: HistoryEntry[]
}

/** Returned by a card to tell the field-source system how to compute
 *  the value for a given source. Cards own the resolution logic
 *  because the data they need (translations, sibling listings, AI
 *  endpoints) varies per card. Sync resolvers return immediately;
 *  async ones drive the diff modal's loading state. */
export type ResolveValue = (
  source: FieldSource,
) => string | null | Promise<string | null>

/** A pending diff modal request. The provider owns one slot — only
 *  one diff modal can be open at a time across the entire cockpit. */
export interface PendingDiff {
  fieldKey: string
  fieldLabel: string
  fromSource: FieldSource
  toSource: FieldSource
  currentValue: string
  nextValue: string
  loading: boolean
  error: string | null
  onConfirm: () => void
  onCancel: () => void
}

export const SOURCE_LABELS: Record<FieldSource, string> = {
  manual:       'Manual',
  master:       'From Master',
  translations: 'From Translations',
  ai:           'AI suggested',
  sibling:      'From Sibling',
  default:      'Default',
}

export const SOURCE_HINTS: Record<FieldSource, string> = {
  manual:       'You typed this directly',
  master:       'Auto-bound to the product master — re-resolves when master changes (unless locked)',
  translations: 'Pulled from the LocalesTab translation for this marketplace',
  ai:           'Generated by AI; once edited becomes Manual',
  sibling:      'Copied from another marketplace listing; once edited becomes Manual',
  default:      'No value set — eBay will reject required fields',
}
