// FF1.1 — MASTER_FIELDS: one entry per editable/notable field of `Product`.
// Source: FF0-FIELD-CENSUS §2 (schema.prisma:83-453).
// scope: 'SHARED' throughout — these map to the `Products` sheet.
// source.model: 'Product' throughout.
//
// Exclusions (per census §3.1 / F15):
//   parentAsin         — F15 duplicate of amazonAsin; excluded
//   fulfillmentChannel — F15 duplicate of fulfillmentMethod; excluded
//   woocommerceProductId — outside active channel scope (MEMORY)
//   masterProductId    — legacy master link; excluded
//   aPlusContent       — rich JSON; excluded (§6)
//   categoryAttributes — arbitrary JSON; excluded (§6)
//   localizedContent   — JSON; flatten per-locale is FFD7; excluded here
//   variantAttributes  — dynamic JSON; excluded (§6)
//   impactProtectors   — JSON; excluded (§6)
//   All image relations, tier prices, relation-only fields — §2.8

import type { FieldDefinition } from './types.js'

export const MASTER_FIELDS: FieldDefinition[] = [
  // ─── §2.1 Identity & structure ───────────────────────────────────────────

  {
    id: 'sku',
    label: 'SKU',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'sku' },
    forcedText: true,
    width: 22,
  },
  {
    id: 'parent_sku',
    label: 'Parent SKU',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'parentId' },
    forcedText: true,
    width: 18,
  },
  {
    id: 'master_sku',
    label: 'Master SKU',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'masterSku' },
    forcedText: true,
    width: 18,
  },
  {
    // F15: isParent / isMaster / isMasterProduct — 3 overlapping flags collapsed
    // into one DERIVED column. source.column is 'isParent' (primary flag).
    id: 'hierarchy_level',
    label: 'Hierarchy Level',
    kind: 'enum',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'isParent' },
    enumOptions: ['PARENT', 'CHILD', 'STANDALONE'],
    enumMode: 'strict',
    width: 14,
  },
  {
    id: 'is_bundle',
    label: 'Is Bundle',
    kind: 'boolean',
    cls: 'SYSTEM',
    scope: 'SHARED',
    source: { model: 'Product', column: 'isBundle' },
    width: 10,
  },
  {
    id: 'variation_theme',
    label: 'Variation Theme',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'variationTheme' },
    width: 18,
  },
  {
    id: 'variation_axes',
    label: 'Variation Axes',
    kind: 'array',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'variationAxes' },
    arrayDelimiter: ' | ',
    width: 20,
  },
  {
    id: 'asin',
    label: 'ASIN',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'amazonAsin' },
    forcedText: true,
    width: 14,
  },
  // parentAsin — EXCLUDED (F15 duplicate of amazonAsin)
  {
    id: 'ebay_item_id',
    label: 'eBay Item ID',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    channel: 'EBAY',
    source: { model: 'Product', column: 'ebayItemId' },
    forcedText: true,
    width: 16,
  },
  {
    id: 'shopify_product_id',
    label: 'Shopify Product ID',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    channel: 'SHOPIFY',
    source: { model: 'Product', column: 'shopifyProductId' },
    forcedText: true,
    width: 20,
  },
  // woocommerceProductId — EXCLUDED (outside active channel scope)
  {
    id: 'upc',
    label: 'UPC',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'upc' },
    forcedText: true,
    width: 16,
  },
  {
    id: 'ean',
    label: 'EAN',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'ean' },
    forcedText: true,
    width: 16,
  },
  {
    id: 'gtin',
    label: 'GTIN',
    kind: 'text',
    cls: 'IDENTITY',
    scope: 'SHARED',
    source: { model: 'Product', column: 'gtin' },
    forcedText: true,
    width: 16,
  },
  {
    // READONLY_SYNCED — cached from SP-API; never round-tripped on import
    id: 'fnsku',
    label: 'FNSKU',
    kind: 'text',
    cls: 'READONLY_SYNCED',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'fnsku' },
    forcedText: true,
    width: 14,
  },

  // ─── §2.2 Editable master content ────────────────────────────────────────

  {
    id: 'name',
    label: 'Name',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'name' },
    width: 30,
  },
  {
    id: 'description',
    label: 'Description',
    kind: 'longtext',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'description' },
    width: 40,
  },
  {
    id: 'bullet_points',
    label: 'Bullet Points',
    kind: 'array',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'bulletPoints' },
    arrayDelimiter: ' | ',
    width: 34,
  },
  {
    id: 'keywords',
    label: 'Keywords',
    kind: 'array',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'keywords' },
    arrayDelimiter: ' | ',
    width: 28,
  },
  {
    id: 'brand',
    label: 'Brand',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'brand' },
    width: 16,
  },
  {
    id: 'manufacturer',
    label: 'Manufacturer',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'manufacturer' },
    width: 18,
  },
  {
    id: 'ebay_title',
    label: 'eBay Title',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    channel: 'EBAY',
    source: { model: 'Product', column: 'ebayTitle' },
    width: 28,
  },
  {
    id: 'product_type',
    label: 'Product Type',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'productType' },
    width: 16,
  },
  {
    id: 'status',
    label: 'Status',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'status' },
    enumOptions: ['DRAFT', 'ACTIVE', 'INACTIVE'],
    enumMode: 'strict',
    width: 10,
  },
  {
    id: 'fulfillment_method',
    label: 'Fulfillment Method',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'fulfillmentMethod' },
    enumOptions: ['FBA', 'FBM'],
    enumMode: 'strict',
    width: 14,
  },
  // fulfillmentChannel — EXCLUDED (F15 duplicate of fulfillmentMethod)
  {
    id: 'shipping_template',
    label: 'Shipping Template',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'shippingTemplate' },
    width: 22,
  },

  // ─── §2.3 Physical / logistics / compliance ───────────────────────────────

  {
    id: 'weight_value',
    label: 'Weight Value',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'weightValue' },
    decimals: 3,
    width: 12,
  },
  {
    id: 'weight_unit',
    label: 'Weight Unit',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'weightUnit' },
    width: 10,
  },
  {
    id: 'dim_length',
    label: 'Dim Length',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'dimLength' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'dim_width',
    label: 'Dim Width',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'dimWidth' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'dim_height',
    label: 'Dim Height',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'dimHeight' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'dim_unit',
    label: 'Dim Unit',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'dimUnit' },
    width: 8,
  },
  {
    id: 'hs_code',
    label: 'HS Code',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'hsCode' },
    width: 12,
  },
  {
    id: 'country_of_origin',
    label: 'Country of Origin',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'countryOfOrigin' },
    width: 14,
  },
  {
    // PPE Directive 2016/425
    id: 'ppe_category',
    label: 'PPE Category',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'ppeCategory' },
    enumOptions: ['CAT_I', 'CAT_II', 'CAT_III'],
    enumMode: 'strict',
    width: 12,
  },
  {
    // EN 17092 motorcycle-gear protection class
    id: 'garment_class',
    label: 'Garment Class (EN 17092)',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'garmentClass' },
    enumOptions: ['AAA', 'AA', 'A', 'B', 'C'],
    enumMode: 'strict',
    width: 14,
  },
  {
    id: 'notified_body_number',
    label: 'Notified Body Number',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'notifiedBodyNumber' },
    width: 20,
  },
  {
    id: 'notified_body_name',
    label: 'Notified Body Name',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'notifiedBodyName' },
    width: 22,
  },
  {
    id: 'doc_url',
    label: 'Declaration of Conformity URL',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'declarationOfConformityUrl' },
    width: 32,
  },
  {
    id: 'hazmat_class',
    label: 'Hazmat Class',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'hazmatClass' },
    width: 12,
  },
  {
    id: 'hazmat_un_number',
    label: 'Hazmat UN Number',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'hazmatUnNumber' },
    width: 16,
  },
  // impactProtectors — EXCLUDED (Json field; flatten or exclude §6)

  // ─── §2.4 Pricing & cost (master-level) ──────────────────────────────────

  {
    id: 'base_price',
    label: 'Base Price',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'basePrice' },
    decimals: 2,
    width: 11,
  },
  {
    id: 'cost_price',
    label: 'Cost Price',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'costPrice' },
    decimals: 2,
    width: 11,
  },
  {
    id: 'min_price',
    label: 'Min Price',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'minPrice' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'max_price',
    label: 'Max Price',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'maxPrice' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'min_margin',
    label: 'Min Margin %',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'minMargin' },
    decimals: 2,
    width: 12,
  },
  {
    id: 'costing_method',
    label: 'Costing Method',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'costingMethod' },
    enumOptions: ['WAC', 'FIFO', 'LIFO'],
    enumMode: 'strict',
    width: 14,
  },
  {
    // DERIVED — recomputed by WAC job; readonly in workbook
    id: 'wac_cents',
    label: 'WAC (Cents)',
    kind: 'number',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'weightedAvgCostCents' },
    width: 12,
  },
  {
    id: 'b2b_price',
    label: 'B2B Price',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'b2bPrice' },
    decimals: 2,
    width: 10,
  },
  {
    id: 'b2b_min_qty',
    label: 'B2B Min Qty',
    kind: 'number',
    cls: 'EDITABLE',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'b2bMinQty' },
    width: 10,
  },
  {
    // READONLY_SYNCED — mirrored from SP-API; ignored on import
    id: 'buybox_price',
    label: 'Buy Box Price',
    kind: 'decimal',
    cls: 'READONLY_SYNCED',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'buyBoxPrice' },
    decimals: 2,
    width: 12,
  },
  {
    // READONLY_SYNCED — mirrored from SP-API; ignored on import
    id: 'competitor_price',
    label: 'Competitor Price',
    kind: 'decimal',
    cls: 'READONLY_SYNCED',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'competitorPrice' },
    decimals: 2,
    width: 14,
  },
  {
    // Replenishment economics — R.4
    id: 'service_level_pct',
    label: 'Service Level %',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'serviceLevelPercent' },
    decimals: 2,
    width: 14,
  },
  {
    id: 'ordering_cost_cents',
    label: 'Ordering Cost (¢)',
    kind: 'number',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'orderingCostCents' },
    width: 16,
  },
  {
    id: 'carrying_cost_pct_year',
    label: 'Carrying Cost % /yr',
    kind: 'decimal',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'carryingCostPctYear' },
    decimals: 2,
    width: 18,
  },

  // ─── §2.5 Stock & derived rollups ────────────────────────────────────────

  {
    // DERIVED — real ledger is StockLevel; cell is a stale echo (readonly)
    id: 'total_stock',
    label: 'Total Stock',
    kind: 'number',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'totalStock' },
    width: 12,
  },
  {
    id: 'low_stock_threshold',
    label: 'Low Stock Threshold',
    kind: 'number',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'lowStockThreshold' },
    width: 18,
  },
  {
    // DERIVED — recomputed weekly by abc-classification job
    id: 'abc_class',
    label: 'ABC Class',
    kind: 'text',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'abcClass' },
    width: 10,
  },
  {
    // DERIVED/SYSTEM — for aging calculations
    id: 'first_inventory_date',
    label: 'First Inventory Date',
    kind: 'date',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'firstInventoryDate' },
    width: 18,
  },
  {
    // DERIVED — linkedToChannels[] + syncChannels[] collapsed; readonly
    id: 'linked_channels',
    label: 'Linked Channels',
    kind: 'array',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'linkedToChannels' },
    arrayDelimiter: ' | ',
    width: 18,
  },
  {
    // DERIVED — overall product validation status
    id: 'validation_status',
    label: 'Validation Status',
    kind: 'enum',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'validationStatus' },
    enumOptions: ['VALID', 'WARNING', 'ERROR'],
    enumMode: 'strict',
    width: 16,
  },
  {
    // DERIVED — validation error messages array; readonly
    id: 'validation_errors',
    label: 'Validation Errors',
    kind: 'array',
    cls: 'DERIVED',
    scope: 'SHARED',
    source: { model: 'Product', column: 'validationErrors' },
    arrayDelimiter: ' | ',
    width: 24,
  },

  // ─── §2.7 System / provenance / lifecycle (selected editable + synced) ────

  {
    // EDITABLE FK to ProductFamily template
    id: 'family_id',
    label: 'Family ID',
    kind: 'text',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'familyId' },
    width: 14,
  },
  {
    // SYSTEM/EDITABLE — internal review workflow state
    id: 'review_status',
    label: 'Review Status',
    kind: 'enum',
    cls: 'EDITABLE',
    scope: 'SHARED',
    source: { model: 'Product', column: 'reviewStatus' },
    enumOptions: ['PENDING_REVIEW', 'APPROVED', 'MERGED'],
    enumMode: 'open',
    width: 16,
  },
  {
    // READONLY_SYNCED — SUCCESS/FAILED/PENDING; ignored on import
    id: 'amazon_sync_status',
    label: 'Amazon Sync Status',
    kind: 'enum',
    cls: 'READONLY_SYNCED',
    scope: 'SHARED',
    channel: 'AMAZON',
    source: { model: 'Product', column: 'amazonSyncStatus' },
    enumOptions: ['SUCCESS', 'FAILED', 'PENDING'],
    enumMode: 'open',
    width: 18,
  },
]
