import { createRequire } from 'node:module'
import { resolve } from 'node:path'
import { draft, variants } from './data.mjs'
import { collectionCards, resolveShopifyContent } from '../../../../../packages/shared/dist/shopify-content.js'
const require = createRequire('/tmp/nexus-impact-verification/package.json'), {Liquid}=require('liquidjs')
const liquid=new Liquid({root:resolve('output/shopify-impact-2026-09-08/theme/snippets'),extname:'.liquid'})
liquid.registerTag('form',{parse(token,remaining){this.templates=[];const stream=this.liquid.parser.parseStream(remaining).on('template',tpl=>this.templates.push(tpl)).on('tag:endform',()=>stream.stop());stream.start()},*render(ctx,emitter){emitter.write('<form>');yield this.liquid.renderer.renderTemplates(this.templates,ctx,emitter);emitter.write('</form>')}})
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')
liquid.registerFilter('image_url',v=>v?.url??v?.src??'')
liquid.registerFilter('image_tag',(src,...args)=>{const a=Object.fromEntries(args.filter(Array.isArray));return `<img src="${esc(src)}" alt="${esc(a.alt)}" width="800" height="800" class="${esc(a.class)}">`})
liquid.registerFilter('money',v=>`€${(Number(v)/100).toFixed(2)}`)
liquid.registerFilter('money_with_currency',v=>`€${(Number(v)/100).toFixed(2)} EUR`)
liquid.registerFilter('t',v=>({ 'product.general.sold_out_badge':'Sold out','product.price.sale_price':'Price' })[v]??v.split('.').at(-1))
liquid.registerFilter('json',v=>JSON.stringify(v??null))
export const groups=collectionCards(draft,variants)
export const collectionFixtureCards=[1,2].flatMap(productId=>groups.map(g=>({key:`${productId}:${g.id}`,label:`${productId===1?'Xavia Racing':'Xavia Touring'} · ${g.label}`,image:`https://fixture.example/${g.label.toLowerCase()}-front.svg`,skus:variants.filter(v=>g.variantIds.includes(v.id)).map(v=>v.sku),productId:`gid://shopify/Product/${productId}`})))
export let collectionOrder=[collectionFixtureCards[1].key,collectionFixtureCards[2].key,collectionFixtureCards[3].key,collectionFixtureCards[0].key]
export const setCollectionOrder=order=>{collectionOrder=order}
export async function collectionPage(url, cardOnly=false){
 const page=Number(url.searchParams.get('page')??(cardOnly&&Number(url.searchParams.get('variant'))>=100?2:1)), filter=url.searchParams.get('filter.v.option.colour'), productId=page===2?2:1
 const media=draft.assets.map((a,i)=>({id:i+101,position:i+1,url:`/media/${a.id}.svg`,width:800,height:800,media_type:'image',alt:a.alt}))
 const native=variants.map((v,i)=>{const r=resolveShopifyContent(draft,v,'en'),m={managed:true,mediaIds:r.assetIds.map(id=>String(draft.assets.findIndex(a=>a.id===id)+101)),alts:Object.fromEntries(draft.assets.map((a,i)=>[i+101,{default:a.alt,en:a.alt}]))};return{id:(productId-1)*100+i+1,sku:v.sku,title:Object.values(v.options).join(' / '),options:Object.values(v.options),available:v.stock>0,matched:!filter||filter===v.options.Colour,price:Number(v.price)*100+(productId===2?1000:0),compare_at_price:0,url:`/en/products/demo?variant=${(productId-1)*100+i+1}`,featured_media:media.find(a=>String(a.id)===m.mediaIds[0]),metafields:{nexus:{resolved:{value:m}}}}})
 const product={id:productId,title:productId===1?'Xavia Racing':'Xavia Touring',handle:'demo',url:'/en/products/demo',price:18900,available:true,media,variants:native,featured_media:media[1],selected_or_first_available_variant:native[0],metafields:{nexus:{resolved:{value:{managed:true,swatches:groups.map(g=>({...g,variantIds:g.variantIds.map(id=>String((productId-1)*100+variants.findIndex(v=>v.id===id)+1))})),cards:groups.map(g=>({...g,variantIds:g.variantIds.map(id=>String((productId-1)*100+variants.findIndex(v=>v.id===id)+1))}))}}}},selling_plan_groups:[]}
 if(cardOnly){const selected=native.find(v=>String(v.id)===url.searchParams.get('variant'))??native[0]; product.selected_or_first_available_variant=selected;return await liquid.renderFile('product-card',{product,section:{id:'card',index:1,settings:{products_per_row_mobile:'2',products_per_row_desktop:2}},settings:{show_sold_out_badge:true,show_discount:false,product_image_aspect_ratio:'square',show_secondary_image:true,product_info_alignment:'left',show_quick_buy:false},request:{locale:{iso_code:'en'}}})}
 const cards=await liquid.renderFile('nexus-impact-collection-cards',{product,section:{id:'collection-demo',index:1,settings:{products_per_row_mobile:'2',products_per_row_desktop:2}},settings:{show_sold_out_badge:true,show_discount:false,product_image_aspect_ratio:'square',show_secondary_image:true,product_info_alignment:'left',show_quick_buy:false},request:{locale:{iso_code:'en'}},position:1})
 const section=`<section id="shopify-section-collection-demo" class="shopify-section"><div class="container"><h1>Collection · Native colour cards</h1><p>Local fixture · Four cards from two Shopify product families · Two server pages</p><nav><a is="facet-link" href="/en/collections/demo">All colours</a> · <a is="facet-link" href="/en/collections/demo?filter.v.option.colour=Red">Red only</a> · <a is="facet-link" href="/en/collections/demo?sort_by=price-ascending">Price: low to high</a></nav><nexus-collection data-collection-id="1" data-pages="2" data-current-page="${page}" data-page-param="page" data-page-size="2" data-product-count="2" data-sort="${esc(url.searchParams.get('sort_by')??'manual')}" data-loading="Loading collection…" data-error="The complete collection could not be loaded." data-retry="Retry" data-count="{count} colour cards" data-page-label="Page"><script type="application/json" data-nexus-order>${JSON.stringify({order:collectionOrder})}</script><p data-nexus-collection-status role="status"></p><nav class="pagination" data-nexus-card-pagination aria-label="Pagination" hidden></nav><div class="collection__results"><product-list class="product-list">${cards}</product-list></div></nexus-collection></div></section>`
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Impact · Collection order preview</title><link rel="stylesheet" href="/theme-assets/theme.css"><link rel="stylesheet" href="/theme-assets/nexus-xavia-customizations.css"><style>:root{--background:255 255 255;--text-color:25 25 25;--border-color:220 220 220;--text-font-family:Arial;--heading-font-family:Arial;--text-base:1rem;--product-list-gap:24px;--product-list-grid:auto-flow / repeat(2,minmax(0,1fr));--product-list-items-per-row:2;--product-card-info-padding:16px}body{font-family:Arial;background:white;color:#191919;padding:24px}.container{max-width:1000px;margin:auto}.product-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.product-list[hidden]{display:none!important}nexus-collection{display:block}.product-card__image{width:100%;height:auto}.product-card__image--secondary{display:none}.pagination{display:flex;gap:16px}.pagination__item{padding:12px;border:1px solid #aaa}a{color:inherit}h1{margin:24px 0;font-size:30px}@media(max-width:600px){.product-list{grid-template-columns:minmax(0,1fr)}}</style><script type="importmap">{"imports":{"vendor":"/theme-assets/vendor.min.js","theme":"/theme-assets/theme.js","photoswipe":"/theme-assets/photoswipe.min.js","nexus-impact":"/theme-assets/nexus-impact.js","nexus-collection":"/theme-assets/nexus-collection.js","nexus-card-swatches":"/theme-assets/nexus-card-swatches.js","nexus-menu-widgets":"/theme-assets/nexus-menu-widgets.js"}}</script><script>window.Shopify={routes:{root:'/en/'},designMode:false};window.themeVariables={settings:{cartType:'drawer',pageType:'collection',reduceMenuAnimation:true},strings:{},breakpoints:{sm:'(min-width:700px)','sm-max':'(max-width:699px)',md:'(min-width:1000px)'}};</script><script type="module" src="/theme-assets/theme.js"></script></head><body><a href="/">Nexus editor</a> · <a href="/en/products/demo">Product preview</a>${section}</body></html>`
}
