import { beforeEach, expect, it, vi } from 'vitest'
const m = vi.hoisted(()=>({db:{category:{findMany:vi.fn()},product:{count:vi.fn()},categoryChannelMapping:{findMany:vi.fn()}},tree:{withLock:vi.fn()}}))
vi.mock('../../db.js',()=>({default:m.db}))
vi.mock('../category-tree.service.js',()=>({categoryTreeService:m.tree,CategoryTreeError:class extends Error{}}))
vi.mock('../pim/schema-mapping.service.js',()=>({getMappingForMarketplace:vi.fn()}))
import { categoryDirectory, categoryChangeImpact } from './category-workspace.js'
const node=(id:string,parentId:string|null=null,depth=0)=>({id,parentId,depth,name:{en:{name:id}},slug:id,code:null,isActive:true,updatedAt:new Date(0),_count:{products:0,children:0,channelMappings:0}})
let rows:ReturnType<typeof node>[]
beforeEach(()=>{vi.resetAllMocks();rows=[node('old'),node('new'),node('child','old',1),node('leaf','child',2)];m.db.category.findMany.mockImplementation(async()=>rows);m.db.product.count.mockResolvedValue(2500);m.db.categoryChannelMapping.findMany.mockResolvedValue([{categoryId:'old',channel:'EBAY',marketplace:'IT',channelCategoryId:'suits',browseNodeId:null},{categoryId:'new',channel:'EBAY',marketplace:'IT',channelCategoryId:'gloves',browseNodeId:null}])})
it('refuses a stale category directory before evaluating a change',async()=>{const directory=await categoryDirectory();rows[0].updatedAt=new Date();await expect(categoryChangeImpact({action:'rename',id:'old',name:'Old name',slug:'old',expectedToken:directory.token})).rejects.toThrow('changed');expect(m.db.product.count).not.toHaveBeenCalled()})
it('blocks moving a populated subtree when inherited channel assignments would change',async()=>{const directory=await categoryDirectory();const impact=await categoryChangeImpact({action:'move',id:'child',parentId:'new',expectedToken:directory.token});expect(impact).toMatchObject({productCount:2500,descendantCount:1,inheritedChanges:['EBAY/IT'],blocked:expect.stringContaining('inherited')})})
it('allows a move after explicit assignments preserve classification for the subtree',async()=>{m.db.categoryChannelMapping.findMany.mockResolvedValue([{categoryId:'child',channel:'EBAY',marketplace:'IT',channelCategoryId:'suits',browseNodeId:null}]);const directory=await categoryDirectory();expect((await categoryChangeImpact({action:'move',id:'child',parentId:'new',expectedToken:directory.token})).blocked).toBeNull()})
it('rejects cycles and deletion of a category with product memberships',async()=>{const directory=await categoryDirectory();await expect(categoryChangeImpact({action:'move',id:'child',parentId:'leaf',expectedToken:directory.token})).rejects.toThrow('descendants');rows[0]._count.products=1;const fresh=await categoryDirectory();expect((await categoryChangeImpact({action:'delete',id:'old',expectedToken:fresh.token})).blocked).toContain('empty category')})
it('preserves complete paths when labels are localized',async()=>{const directory=await categoryDirectory();expect(directory.rows.find(c=>c.id==='leaf')?.path).toBe('old › child › leaf')})
