// ── eBay aspect name → English translation dictionary ───────────────────
//
// The Taxonomy API always returns aspect names in the marketplace language
// (Accept-Language is ignored). We maintain a static lookup so the UI can
// show the English meaning alongside the localized label.
//
// Covers IT, DE, FR, ES — the four non-English eBay markets Xavia sells on.
// Keys are lower-cased; the lookup is case-insensitive.

const ASPECT_EN: Record<string, string> = {
  // ── Italian (IT) ──────────────────────────────────────────────────────
  'marca': 'Brand',
  'taglia': 'Size',
  'colore': 'Color',
  'materiale': 'Material',
  'genere': 'Gender',
  'tipo': 'Type',
  'stile': 'Style',
  'stagione': 'Season',
  'modello': 'Model',
  'produttore': 'Manufacturer',
  'numero di serie': 'Serial number',
  'lunghezza manica': 'Sleeve length',
  'vestibilità': 'Fit',
  'vestibilita': 'Fit',
  'caratteristiche': 'Features',
  'paese di fabbricazione': 'Country of manufacture',
  'peso': 'Weight',
  'peso del prodotto': 'Product weight',
  'lunghezza': 'Length',
  'larghezza': 'Width',
  'altezza': 'Height',
  'dimensioni': 'Dimensions',
  'occasione': 'Occasion',
  'motivo': 'Pattern',
  'chiusura': 'Closure / Fastening',
  'protezione': 'Protection',
  'livello di protezione': 'Protection level',
  'impermeabile': 'Waterproof',
  'certificazione': 'Certification',
  'norma': 'Standard',
  'taglia produttore': 'Manufacturer size',
  'linea': 'Line',
  'collezione': 'Collection',
  'anno': 'Year',
  'reparto': 'Department',
  'tipo di tessuto': 'Fabric type',
  'composizione': 'Composition',
  'numero articolo fornitore': 'Supplier part number',
  'ean': 'EAN',
  'isbn': 'ISBN',
  'mpn': 'MPN',
  'upc': 'UPC',

  // ── German (DE) ───────────────────────────────────────────────────────
  'marke': 'Brand',
  'größe': 'Size',
  'grösse': 'Size',
  'farbe': 'Color',
  'material': 'Material',
  'abteilung': 'Department',
  'stil': 'Style',
  'modell': 'Model',
  'hersteller': 'Manufacturer',
  'saison': 'Season',
  'passform': 'Fit',
  'anlass': 'Occasion',
  'muster': 'Pattern',
  'verschluss': 'Closure',
  'thema': 'Theme',
  'herstellernummer': 'Manufacturer part number',
  'herstellungsland und -region': 'Country of manufacture',
  'produktart': 'Product type',
  'produktlinie': 'Product line',
  'type': 'Type',
  'länge': 'Length',
  'breite': 'Width',
  'höhe': 'Height',
  'gewicht': 'Weight',
  'schutzklasse': 'Protection class',
  'wasserdicht': 'Waterproof',
  'zertifizierung': 'Certification',
  'norm': 'Standard',
  'herstellergröße': 'Manufacturer size',
  'herstellergroesse': 'Manufacturer size',
  'kollektion': 'Collection',
  'jahr': 'Year',
  'stoff': 'Fabric',
  'zusammensetzung': 'Composition',
  'artikelnummer des herstellers': 'Manufacturer part number',
  'eu-schuhgröße': 'EU shoe size',

  // ── French (FR) ───────────────────────────────────────────────────────
  'marque': 'Brand',
  'taille': 'Size',
  'couleur': 'Color',
  'matière': 'Material',
  'matiere': 'Material',
  'département': 'Department',
  'departement': 'Department',
  'modèle': 'Model',
  'coupe': 'Fit',
  'motif': 'Pattern',
  'fermeture': 'Closure',
  'thème': 'Theme',
  'pays de fabrication': 'Country of manufacture',
  'type de produit': 'Product type',
  'longueur': 'Length',
  'largeur': 'Width',
  'hauteur': 'Height',
  'poids': 'Weight',
  'imperméable': 'Waterproof',
  'annee': 'Year',
  'tissu': 'Fabric',
  'référence du fabricant': 'Manufacturer part number',
  'numéro de pièce fabricant': 'Manufacturer part number',

  // ── Spanish (ES) ──────────────────────────────────────────────────────
  'talla': 'Size',
  'color': 'Color',
  'departamento': 'Department',
  'modelo': 'Model',
  'temporada': 'Season',
  'ajuste': 'Fit',
  'ocasión': 'Occasion',
  'ocasion': 'Occasion',
  'estampado': 'Pattern',
  'cierre': 'Closure',
  'tema': 'Theme',
  'país de fabricación': 'Country of manufacture',
  'tipo de producto': 'Product type',
  'longitud': 'Length',
  'anchura': 'Width',
  'altura': 'Height',
  'protección': 'Protection',
  'proteccion': 'Protection',
  'impermeable': 'Waterproof',
  'certificación': 'Certification',
  'colección': 'Collection',
  'coleccion': 'Collection',
  'ano': 'Year',
  'tela': 'Fabric',
  'composición': 'Composition',
  'composicion': 'Composition',
  'número de pieza del fabricante': 'Manufacturer part number',
}

export function lookupEnglishAspectName(localizedName: string): string | undefined {
  const key = localizedName.trim().toLowerCase()
  return ASPECT_EN[key]
}

// These names were missing from cached category metadata. Resolve them for UI labels only:
// adding display translations must not rename existing aspect keys or publishing addresses.
const DISPLAY_NAMES: Record<string, string> = {
  'adatto a': 'Suitable for',
  'adatta': 'Fit',
  'colore esatto': 'Exact color',
  'colore specifico': 'Specific color',
  "cura dell'indumento": 'Garment care',
  'garanzia produttore': 'Manufacturer warranty',
  'paese di origine': 'Country of origin',
  'quantità': 'Quantity',
  'quantita': 'Quantity',
  'scollatura': 'Neckline',
  'unità di misura': 'Unit of measure',
  'unita di misura': 'Unit of measure',
  'età': 'Age',
  'eta': 'Age',
  'certificazione ce': 'CE certification',
  'tipo di prodotto': 'Product type',
  'materiale specifico': 'Specific material',
  'materiale esatto': 'Exact material',
  'caratteristiche aggiuntive': 'Additional features',
  'armatura': 'Armor',
}

/** Translate a heading without changing the marketplace's name or the field's stable key. */
export function englishEbayAspectLabel(name: string): string | undefined {
  const normalized = name.trim().replace(/[’‘]/g, "'").replace(/\s+/g, ' ')
  return DISPLAY_NAMES[normalized.toLowerCase()] ?? lookupEnglishAspectName(normalized)
}
