import { afterAll, beforeAll, expect, it, vi } from 'vitest'
import Fastify from 'fastify'
const mocks = vi.hoisted(() => ({ write: vi.fn() }))
vi.mock('../db.js', () => ({ default: { bulkActionJob: { create: mocks.write }, channelListing: { update: mocks.write } } }))
vi.mock('../lib/api-key-hook.js', () => ({ allowApiKeyScope: () => async () => {} }))
vi.mock('../services/listing-events.service.js', () => ({ publishListingEvent: vi.fn(), subscribeListingEvents: vi.fn() }))
vi.mock('../services/product-event.service.js', () => ({ productEventService: {} }))
vi.mock('../services/ai/providers/index.js', () => ({ getProvider: vi.fn() }))
vi.mock('../services/amazon-publish-gate.service.js', () => ({ getAmazonPublishMode: vi.fn(), isAmazonPublishEnabled: vi.fn() }))
vi.mock('../services/ebay-publish-gate.service.js', () => ({ getEbayPublishMode: vi.fn(), isEbayPublishEnabled: vi.fn() }))
vi.mock('../services/shopify-publish-gate.service.js', () => ({ getShopifyPublishMode: vi.fn(), isShopifyPublishEnabled: vi.fn() }))
vi.mock('../services/amazon-participations.service.js', () => ({ refreshAmazonParticipations: vi.fn() }))
vi.mock('../services/bulk-action.service.js', () => ({ KNOWN_BULK_ACTION_TYPES: new Set(['LISTING_BULK_ACTION']) }))
vi.mock('../services/fulfillment-derivation.service.js', () => ({ deriveFulfillmentMethod: vi.fn() }))
vi.mock('../services/follow-master.service.js', () => ({ setFollowMasterQuantity: vi.fn(), setStockBuffer: vi.fn() }))
vi.mock('../services/outbound-enqueue.js', () => ({ fireOutboundJobs: vi.fn() }))
vi.mock('../services/connection-resolver.service.js', () => ({ tryResolveConnection: vi.fn() }))
import { listingsSyndicationRoutes } from './listings-syndication.routes.js'
const app = Fastify()
beforeAll(async () => { await app.register(listingsSyndicationRoutes) })
afterAll(async () => { await app.close() })
it.each(['publish', 'unpublish'])('refuses legacy %s before creating a job or changing a listing flag', async action => {
  const response = await app.inject({ method: 'POST', url: '/listings/bulk-action', payload: { action, listingIds: ['listing-a'] } })
  expect(response.statusCode).toBe(409)
  expect(response.json()).toMatchObject({ code: 'CHANNEL_WORKFLOW_REQUIRED', reviewHref: '/products/listing-readiness' })
  expect(mocks.write).not.toHaveBeenCalled()
})
it.each([true, false])('refuses a generic isPublished=%s patch without changing local state', async isPublished => {
  const response = await app.inject({ method: 'PATCH', url: '/listings/listing-a', payload: { isPublished } })
  expect(response.statusCode).toBe(409)
  expect(response.json()).toMatchObject({ code: 'CHANNEL_WORKFLOW_REQUIRED' })
  expect(mocks.write).not.toHaveBeenCalled()
})
it.each(['_nexusLinkedAutomation', '_nexusLinkedProducts', '_nexusLinkedProductsOperation'])('refuses a generic %s patch before any database write', async key => {
  const response = await app.inject({ method: 'PATCH', url: '/listings/listing-a', payload: { platformAttributes: { [key]: { mode: 'AUTOMATIC' } } } })
  expect(response.statusCode).toBe(409)
  expect(response.json()).toMatchObject({ code: 'SHOPIFY_WORKSPACE_REQUIRED' })
  expect(mocks.write).not.toHaveBeenCalled()
})
