'use client'

/**
 * Shared "Rules" block (Helium 10 match) — Keyword Harvesting / Negative Targeting tabs, each its
 * own Rule Name + Automate + Search-Term-Isolation + the ad-group × target-type matrix (Look for
 * search terms · create Broad/Phrase/Exact/Product targets · create negative Phrase/Exact/Product)
 * + a collapsible Performance Criteria. The matrix selections live in `RulesConfig.sel`, which the
 * launch endpoints turn into `harvest_and_negate` AutomationRules and the RuleControlPanel canvas
 * reads back.
 *
 * Extracted here so the Guided builder reuses the exact same control as the SP Super Wizard's
 * Step-3. Reuses the shared rule model (RulesConfig/RuleRowSel from LaunchStep), the shared
 * PerformanceCriteria, and the existing `.h10-spw-rules`/`.h10-spw-mx` styles in ads.css.
 * (SP Super Wizard's LaunchStep still renders its own inline copy for now — a later pass can point
 * it here to dedupe; the model + engine are already shared, so behaviour matches.)
 */
import { type Dispatch, type SetStateAction, useState } from 'react'
import { Layers } from 'lucide-react'
import { InfoTip } from '../campaigns/InfoTip'
import { PerformanceCriteria, type CriteriaGroup } from '../rules-automation/_shared/PerformanceCriteria'
import { emptyRuleRow, type RuleRowSel, type RulesConfig } from '../campaign-builder/sp-super-wizard/LaunchStep'
import type { SpwCampaign } from '../campaign-builder/sp-super-wizard/CampaignSetup'
import type { AdProduct } from './CampaignTypeSelect'

type RuleCampaign = SpwCampaign & { adProduct?: AdProduct }

function KindBadge({ kind, adProduct }: { kind: SpwCampaign['kind']; adProduct?: AdProduct }) {
  const auto = kind === 'auto'
  return <><span className={`h10-spw-kb ${auto ? 'a' : 'm'}`}>{auto ? 'A' : 'M'}</span><span className="h10-spw-spb">{adProduct ?? 'SP'}</span></>
}

function MBadge({ tone, letter }: { tone: 'green' | 'slate' | 'navy' | 'blue' | 'maroon'; letter?: string }) {
  return <span className={`h10-spw-mb ${tone}`}>{letter ?? <Package11 />}</span>
}
function Package11() { return <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" aria-hidden><path d="M21 8 12 3 3 8l9 5 9-5Z" /><path d="m3 8 0 8 9 5 9-5 0-8" /></svg> }

function Check({ on, disabled, onChange, label }: { on: boolean; disabled?: boolean; onChange: () => void; label: string }) {
  if (disabled) return <span className="h10-spw-mx-ck dis" aria-hidden />
  return <input type="checkbox" className="h10-spw-mx-ck" checked={on} onChange={onChange} aria-label={label} />
}

export function HarvestRules({ rules, setRules, campaigns }: {
  rules: { harvest: RulesConfig; negative: RulesConfig }
  setRules: Dispatch<SetStateAction<{ harvest: RulesConfig; negative: RulesConfig }>>
  campaigns: RuleCampaign[]
}) {
  const [tab, setTab] = useState<'harvest' | 'negative'>('harvest')
  const [perfOpen, setPerfOpen] = useState(false)
  const isNeg = tab === 'negative'
  const active = rules[tab]
  const { ruleName, automate, sel, perf } = active
  const setActive = (patch: Partial<RulesConfig>) => setRules((r) => ({ ...r, [tab]: { ...r[tab], ...patch } }))
  const setRuleName = (v: string) => setActive({ ruleName: v })
  const setAutomate = (v: boolean) => setActive({ automate: v })
  const rowSel = (id: string) => sel[id] ?? emptyRuleRow()
  const setRow = (id: string, patch: Partial<RuleRowSel>) => setActive({ sel: { ...sel, [id]: { ...(sel[id] ?? emptyRuleRow()), ...patch } } })
  const setPerf = (g: CriteriaGroup) => setActive({ perf: g })
  const tEnabled = (k: SpwCampaign['kind']) => ({ B: k === 'keyword', P: k === 'keyword', E: k === 'keyword', box: k === 'pat' })
  const nEnabled = (k: SpwCampaign['kind']) => ({ P: k !== 'pat', E: k !== 'pat', box: k !== 'keyword' })

  return (
    <div className="h10-spw-rules">
      <h3>Rules</h3>
      <p className="h10-spw-desc">All rules affecting an ad group will appear underneath it. Suggestions generated by rules will appear on the Suggestions Page.</p>
      <div className="h10-spw-rules-tabs" role="tablist">
        <button type="button" role="tab" aria-selected={tab === 'harvest'} className={tab === 'harvest' ? 'on' : ''} onClick={() => setTab('harvest')}>Keyword Harvesting</button>
        <button type="button" role="tab" aria-selected={tab === 'negative'} className={tab === 'negative' ? 'on' : ''} onClick={() => setTab('negative')}>Negative Targeting</button>
      </div>

      <label className="h10-spw-rules-rn">
        <span className="l">Rule Name</span>
        <input value={ruleName} onChange={(e) => setRuleName(e.target.value)} placeholder="Enter a rule name" aria-label="Rule name" />
      </label>
      <label className="h10-spw-rules-auto">
        <input type="checkbox" className="h10-spw-sw" checked={automate} onChange={(e) => setAutomate(e.target.checked)} />
        <span>Automate</span>
      </label>
      <p className="h10-spw-rules-autohint">On a schedule, this rule proposes its harvested {isNeg ? 'negatives' : 'keywords & negatives'} on the <strong>Suggestions</strong> page for you to approve — it never changes campaigns on its own.</p>

      <div className={`h10-spw-mx ${isNeg ? 'neg' : ''}`}>
        <div className="h10-spw-mx-grid grp">
          <span className="ql">What Ad Groups would you like included in this rule?</span>
          <span className="qr">What {isNeg ? 'negative targets' : 'targets'} would you like created? <InfoTip tip={isNeg ? 'Negative keyword / product targets to add from these search terms.' : 'New keyword/product targets created from harvested search terms.'} /></span>
        </div>
        <div className="h10-spw-mx-grid sub">
          <span className="c-ag">Ad Group</span>
          <span className="c-st">Look for Search Terms in These Ad Groups <InfoTip tip="Harvest converting search terms from these ad groups." /></span>
          {!isNeg && <span className="c-t">Create New Targets <InfoTip tip="Match types of new positive targets to create." /></span>}
          <span className="c-n">Create New Negative Targets</span>
        </div>
        <div className="h10-spw-mx-grid badges">
          {!isNeg && <><span className="b3"><MBadge tone="green" letter="B" /></span>
          <span className="b4"><MBadge tone="slate" letter="P" /></span>
          <span className="b5"><MBadge tone="navy" letter="E" /></span>
          <span className="b6"><MBadge tone="blue" /></span></>}
          <span className="b8"><MBadge tone="maroon" letter="P" /></span>
          <span className="b9"><MBadge tone="maroon" letter="E" /></span>
          <span className="b10"><MBadge tone="maroon" /></span>
        </div>
        {campaigns.map((c) => {
          const r = rowSel(c.id); const te = tEnabled(c.kind); const ne = nEnabled(c.kind)
          return (
            <div className="h10-spw-mx-grid row" key={c.id}>
              <div className="c-ag id"><KindBadge kind={c.kind} adProduct={c.adProduct} /><div className="nm"><span className="t">{c.name}</span><span className="ag"><Layers size={12} /> {c.adGroupName}</span></div></div>
              <div className="c-st"><Check on={r.st} onChange={() => setRow(c.id, { st: !r.st })} label={`Look for search terms in ${c.name}`} /></div>
              {!isNeg && <>
                <div className="b3"><Check on={r.tB} disabled={!te.B} onChange={() => setRow(c.id, { tB: !r.tB })} label={`Create Broad target for ${c.name}`} /></div>
                <div className="b4"><Check on={r.tP} disabled={!te.P} onChange={() => setRow(c.id, { tP: !r.tP })} label={`Create Phrase target for ${c.name}`} /></div>
                <div className="b5"><Check on={r.tE} disabled={!te.E} onChange={() => setRow(c.id, { tE: !r.tE })} label={`Create Exact target for ${c.name}`} /></div>
                <div className="b6"><Check on={r.tBox} disabled={!te.box} onChange={() => setRow(c.id, { tBox: !r.tBox })} label={`Create product target for ${c.name}`} /></div>
              </>}
              <div className="b8"><Check on={r.nP} disabled={!ne.P} onChange={() => setRow(c.id, { nP: !r.nP })} label={`Create negative Phrase for ${c.name}`} /></div>
              <div className="b9"><Check on={r.nE} disabled={!ne.E} onChange={() => setRow(c.id, { nE: !r.nE })} label={`Create negative Exact for ${c.name}`} /></div>
              <div className="b10"><Check on={r.nBox} disabled={!ne.box} onChange={() => setRow(c.id, { nBox: !r.nBox })} label={`Create negative product for ${c.name}`} /></div>
            </div>
          )
        })}
      </div>

      <button type="button" className="h10-spw-perf" onClick={() => setPerfOpen((o) => !o)}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={perfOpen ? 'up' : ''} aria-hidden><path d="m6 9 6 6 6-6" /></svg> Performance Criteria</button>
      {perfOpen && (
        <div className="h10-spw-perf-body">
          <p>Only act on search terms that meet these performance thresholds (optional).</p>
          <PerformanceCriteria value={perf} onChange={setPerf} slug={isNeg ? 'negative-targeting' : 'keyword-harvesting'} />
        </div>
      )}
    </div>
  )
}
