from pathlib import Path
import json,hashlib
from datetime import datetime,timezone
p=Path('docs/audits/2026-09-12-language-axis/step3-switch')
read=lambda f:json.loads((p/f).read_text())
now=datetime.now(timezone.utc).isoformat();source=read('source-manifest.json');api=read('final-api-tests.json');web=read('web-wire-tests.json');prod=read('measured-production-shadow.json');replay=read('wire-expectation-replay.json');by=read('counts-by-language.json');guard=read('guard-output.json')
assert api['success'] and web['success'] and replay['correctedDiffs']==0
assert all(c['exitCode']==0 for c in read('checks.json')+read('final-scope-check.json'))
lines=[
'\n\n### LX Step 3 — §4 final reader-switch record — STOPPED AT THE STEP 3 GATE',
'',f'Recorded {now}. Owner accepted Q-LX3-1 (R10/R2/R6/R7/R8, zero unclassified, both resolver defects acknowledged). This completes the authorized reader switch; Step 4 has not started. All work remains uncommitted and unpushed. Deployment remains the Owner’s.',
'', '**Implementation and decisions.** LX.4 and Appendix B readers now use the single language-only normalizer and content resolver. `content-resolver.ts:66` defaults the source flag to v2; `:67` defines operator-pin eligibility and `:69` defines missingness by actual/requested language. `DEFAULT_LOCALE` and the former product-content cascades are deleted. No environment/deployment flag was written. Explicitly disabling v2 refuses the new resolver; this record does not claim a flag-off restoration of deleted legacy readers. No regional key folding or data backfill exists. The detailed producer/consumer and writer-exception inventory is [boundary-integration.md](audits/2026-09-12-language-axis/step3/boundary-integration.md).',
'', '**Owner conditions.** All translation-missing consumers are listed in that inventory: readiness, coverage endpoints and command matrix, AI targeting, mapping/formula sources, catalogue preview/export, and store adapters. They use resolved language; required emptiness is separate. LX.5’s required-language rule is implemented now in `readiness.service.ts:209`; the index remains Step 5. The positive-control test in `content-readiness.vitest.test.ts` blocks non-empty Italian fallback for German, then accepts German. Following R2 rows expose follows=true/drift=true and inherited provenance; `isOperatorContentPin` excludes them for Step 4. Sheet/API list wires retain `[]`, including fields metadata; explicit child-clear regression remains. Both frontend mirrors accept the existing language facts, and the channel mirror now declares channelSnapshot without changing layout or controls.',
'', '**R2 query-only split.** Production snapshot 2026-09-12T06:53:09.264Z, READ ONLY and ROLLBACK, exit 0. The 866 observations refer to 575 unique listings; no shadow rerun was used for this split. [Exact flags](audits/2026-09-12-language-axis/step3-switch/r2-flags.json).',
'', '| Field | follow=true: drift | follow=false: operator pin | null |','|---|---:|---:|---:|','| title | 365 | 279 | 0 |','| description | 222 | 0 | 0 |','| Total observations | 587 | 279 | 0 |',
'', '**Production shadow measurement.** Exactly one switched-reader production run, via Railway production / @nexus/api, snapshot **2026-09-12T08:00:15.514Z**, READ ONLY + REPEATABLE READ, rolledBack=true. Family: XAVIA / GALE-JACKET (`cmokmy3a40078pm0p1fvnu523`), 21 rows. Whole catalogue: 338 products, 37 roots, 977 listings, 20 account/alias-aware coordinates, 71 fields (4 core + 67 declared custom), 9 languages, 1 ProductTranslation. 1,171,843 comparisons: original 692,203 plus 479,640 added sheet-wire observations. Every one of the 14,033 accepted next values was checked: **0 mismatches, 0 omissions**. All 13 selected-table hashes match the accepted snapshot.',
'', '**Raw result and instrument correction — preserved, not hidden.** The raw production command exited **1**, gate HOLD, because its added sheet-wire matrix compared one projected list against a raw array: GALE-JACKET-BLACK-MEN-XL / Amazon IT / bulletPoints, empty fourth slot. The pre-existing `sheet-values.ts:68` projector removes blank members from an unbounded list; its full bytes and SHA are unchanged. Under the Owner’s unchanged-wire condition, the expected wire must use that same projection. An offline replay of only the captured observation proves the 4-item wire equals the accepted 5-slot array’s established projection. It also rejects loss of a non-empty item and preserves null for the individual empty slot. **Verified behavior differences: 0**. No application reader was changed to erase this mismatch; all 30 measured application-reader hashes remain identical. No production query or shadow was rerun. This corrects an instrument expectation; it introduces no content reclassification.',
'', 'Raw evidence: [measured-production-shadow.json](audits/2026-09-12-language-axis/step3-switch/measured-production-shadow.json), [measured-production-diffs.json.gz](audits/2026-09-12-language-axis/step3-switch/measured-production-diffs.json.gz). Offline correction: [wire-expectation-replay.json](audits/2026-09-12-language-axis/step3-switch/wire-expectation-replay.json), exit **0**. The raw report retains its original HOLD result. The rerunnable instrument is `step3-switch/build-shadow.mjs` → `shadow.mjs`; its corrected list expectation passes the same 15/15 offline controls, 282 comparisons. Neither the old accepted shadow nor production was run again.',
'', '**Counts by field and language.** All 71 × 9 field/language totals are in [counts-by-field-language.md](audits/2026-09-12-language-axis/step3-switch/counts-by-field-language.md); reader/field/language detail is in [verified-counts-by-field-language.json](audits/2026-09-12-language-axis/step3-switch/verified-counts-by-field-language.json). Raw counts remain separately preserved. The following totals use the verified wire expectation:',
'', '| Language | All reader comparisons | Main product × coordinate × field | Verified differences |','|---|---:|---:|---:|',
]
for r in by:lines.append(f"| {r['language']} | {r['compared']:,} | {r['mainCompared']:,} | {r['diffs']} |")
lines+=['','| Reader | Comparisons | Verified differences |','|---|---:|---:|']
for reader in sorted({c['reader'] for c in replay['counts']}):
 cs=[c for c in replay['counts'] if c['reader']==reader];lines.append(f"| {reader} | {sum(c['compared'] for c in cs):,} | {sum(c['diffs'] for c in cs)} |")
lines += [
'', 'Production Etsy/Shopify reader populations are **0**, not claimed as production-tested positives. The same-run offline fixture covers both store readers, both Belgium languages, two accounts, an unlisted child, parent translation, explicit clear, and an injected sheet defect that fails the instrument.',
'', '**Tests and checks.**',
'', f'- API: **{api["numPassedTests"]}/{api["numTotalTests"]} tests**, 18 files, final command exit **0**; `final-api-tests.json` and `final-api-test-command.json` preserve times and commands. Includes core/shadow, readiness, coverage/AI/catalogue, mapping, actual disposable API sheets/accounts/aliases, media, authority and built DE/BE-nl/BE-fr/UK payloads. No provider call.',
 f'- Web node-only: **{web["numPassedTests"]}/{web["numTotalTests"]} tests**, 3 files, exit **0** (2 language-wire parity, 24 channel provenance, 40 DS provenance). `web-wire-tests.json`.',
 '- Shared media: **5/5**, exit **0**. Total final unit cases across these suites: **251**. Normalization fixture now expects fr from fr-CA as D4 requires.',
 '- API scoped types: **70 inputs plus transitive imports**, clean, exit **0**. Web scoped types: **2 inputs plus ambient/transitive imports**, clean, exit **0**. Shared language/media strict typecheck exit **0**. These are scoped checks, not full-workspace typecheck claims.',
 f'- LX.2 guard: **2/2**, exit **0**; scanned **{guard["scanned"]}** tracked/untracked API runtime sources, **{len(guard["exempt"])}** Owner-exempt runtime paths, **0 violations**. Exact output below and in `guard-output.json`.',
 '- Offline shadow positive controls: **15/15**, exit **0**, 282 comparisons; non-vacuous injected defect rejected. Offline captured-wire replay: exit **0**. Scoped `git diff --check`: exit **0**; untracked source changes are included in the independent byte/mtime manifest and full source diff.',
 '- Earlier failures were corrected and retained in the narrative: missing listing workspace hydration; legacy JSON fixture expectations; automatic duplicate primary-language export rows; unit fixture’s regional media expectation; parity test’s imported-type/path handling. The sandbox blocked a disposable test socket and Railway before production access; authorized retries succeeded. None of those attempts is reported as a passing measurement.',
 '- The Owner-attributed amazon-sp-client.ts diagnostics at lines 85/87 remain recorded in `step2/shared-type-diagnostics.json`; that file was not edited. Current scoped checks emit no diagnostics for it; this does not attribute or claim to fix the other session’s work.',
'', '```json', json.dumps(guard,indent=2),'```',
'', '**Screen and restore.** This is the server/read layer for the Product Edit Studio’s shared and channel sheets. No screen layout/control changed, no visible Languages view is claimed, and no browser gate was run; Step 6 owns the visible walkthrough and retirement of the old editor. Unit sheet checks use a disposable fixture API/database and mocked providers. No rehearsal or business-data write ran on XAVIA or elsewhere; exact production cleanup was **ROLLBACK** of the read-only transaction, so no restore-by-value was necessary. No schema/migration, provider call, publish rehearsal, push or deploy. Protected runtime files, the previously authorized GPSR test fixture and the SDK compare **28/28 unchanged** to this switch’s start in `protected-files.json`.',
'', '**Scope and review receipt.** 78 claimed source/test/doc paths, 77 changed; one claimed projector is unchanged. Before bytes are preserved in `before.json`; new helper creation was claimed in the initial switch entry. [Full switch diff](audits/2026-09-12-language-axis/step3-switch/step3-switch-source.diff) includes untracked files. The prior accepted Step 3 diff remains in `step3/step3-source.diff`. File hashes below identify full contents, not ownership of any earlier unrelated lines. All audit artifacts and this ledger snapshot are inventoried in `step3-switch/manifest.json` (excluding the manifest’s self-hash).',
'', '| File | mtime UTC | SHA-256 |','|---|---|---|',
]
for row in source:
 lines.append(f"| `{row['file']}` | {row['mtime'] or 'archived/removed from application source'} | `{row['sha256'] or 'see accepted-shadow-source.ts.txt'}` |")
lines+=['', '**Open questions: none about behavior or scope.** The original accepted classifications stand; the instrument expectation correction and its raw/derived receipts are exposed above for Step 3 review. **STOP: Step 3 gate; no Step 4 work.**','']
body='\n'.join(lines)
ledger=Path('docs/pes-claims.md')
assert '### LX Step 3 — §4 final reader-switch record — STOPPED AT THE STEP 3 GATE' not in ledger.read_text()
start=len(ledger.read_text().splitlines())+3
with ledger.open('a') as f:f.write(body)
(p/'record-location.json').write_text(json.dumps({'recordedAt':now,'file':'docs/pes-claims.md','line':start},indent=2)+'\n')
# Evidence hashes after the once-only ledger entry. Preserve accepted evidence; never rewrite its reports.
artifacts=[]
for path in sorted(p.rglob('*')):
 if path.is_file() and path.name!='manifest.json':
  artifacts.append({'file':str(path),'mtime':datetime.fromtimestamp(path.stat().st_mtime,timezone.utc).isoformat(),'bytes':path.stat().st_size,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
artifacts.append({'file':str(ledger),'mtime':datetime.fromtimestamp(ledger.stat().st_mtime,timezone.utc).isoformat(),'bytes':ledger.stat().st_size,'sha256':hashlib.sha256(ledger.read_bytes()).hexdigest()})
(p/'manifest.json').write_text(json.dumps({'recordedAt':now,'sourceFiles':source,'evidenceFiles':artifacts},indent=2)+'\n')
print(json.dumps({'recordLine':start,'sourceFiles':len(source),'evidenceFiles':len(artifacts),'unitTests':251,'verifiedDiffs':0,'rawInstrumentMismatches':1,'productionShadowRuns':1}))
