from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
root=Path.cwd();here=root/'docs/audits/2026-09-12-language-axis/step4';ledger=root/'docs/pes-claims.md'
read=lambda name:json.loads((here/name).read_text())
manifest=read('source-manifest.json');api=read('final-api-tests.json');web=read('final-web-tests.json');guard=read('guard-output.json');audit=read('final-local-read.json')
assert api['numFailedTests']==0 and api['numPassedTests']==95
assert web['numFailedTests']==0 and web['numPassedTests']==40
assert not guard['violations']
assert all(row['unchanged'] for row in read('protected-check.json')['files'])
assert read('typecheck-receipt.json')['exitCode']==0
assert not read('final-provider-evidence.json')['providerAttempts']
base=read('fixture-baseline.json')
for phase in ['master-primary','master-german-final','channel-pin','acknowledged-shared','drift-cell']:
 assert read(f'fixture-{phase}-restored.json')['data']==base['data']
now=datetime.now(timezone.utc).isoformat()
lines=[f'\n## Language axis · Step 4 · §4 record · {now}\n',
'**Gate status: implementation and all six local fixture paths verified; Step 4 remains OPEN for Q-LX4-1 (strict editor authentication). Step 5 has not started.**\n',
'**Scope and behavior.** The changed page is the **Product Edit Studio**, `/products/:id/edit/studio`, Information sheet, Shared product and channel scopes. LX.8 routes every addressed sheet edit through the server column contract. Primary text stays on Product; non-primary shared text uses `translation-write.ts` with review/source stamps and Product/translation CAS; pins use ChannelListingTranslation. Only `tier=pin && follows=false` edits directly as an operator pin. Inherited and drift cells show both shared/pin answers; decline restores the displayed value without a request. Paste and fill use the same gate, router and validator. Every language-tier caller runs the same-language cascade transactionally, including bulk, review/removal, formulas and mapping-generated drafts; audit metadata includes language. New pin rows are hydrated by the consuming readers. Boundary inventory: [boundary-integration.md](audits/2026-09-12-language-axis/step4/boundary-integration.md).\n',
'**Migration receipt.** One folder: `20260912_lx4_channel_listing_translations`; SHA256 `1ce46b3a34aaf43563554e2033c5f224cf38d8f963b75d43018e4892b234046b`. New table, its keys/indexes/FK and permission on that new table only; no trigger/function or changes to existing columns/values. The `follows` array is a per-field reset marker in the new table, allowing legacy read-through to be suppressed without changing legacy text. Before/after announcements are above in this ledger. Local: execute 12:50:22.578Z→exit 0; resolve 12:50:28.592Z→exit 0. Production: execute 12:50:44.316Z→exit 0; resolve 12:50:53.544Z→exit 0. Both used `prisma db execute --file` followed by `prisma migrate resolve --applied`, never deploy. The read-only verification transactions rolled back: local 12:51:05.283Z, production 12:55:58.879Z; table empty, matching applied checksum, zero added/removed/changed rows in Product, ProductTranslation, ChannelListing and Marketplace, legacy read-only trigger absent. Sandbox connection/execute attempts failed before approved retries; those were not successful schema operations. Receipts: `step4/{local,production}-{before,execute,resolve,after}.json`.\n',
'**Local fixture and measurement.** XAVIA GALE, parent `cmokmy3a40078pm0p1fvnu523` (`GALE-JACKET`), fixed variant `cmokmy0lr0009pm0p9yxk7ho0` (`GALE-JACKET-BLACK-MEN-XS`), Amazon DE listing `cmp00tsac0037s101ijg2of6x`. Database: `127.0.0.1:55439/nexus_development`; baseline at 14:36:17.947Z. Actual studio components and Fastify routes/services ran on owned loopback ports 3154/4119, with local cached schemas instead of provider schema reads. External transports were blocked. New fixture queue rows were held until 2099 inside the same transaction before commit, then removed at restore. Existing local workers could never see an eligible rehearsal queue. No production business-data write or provider/publish call occurred.\n',
'| Path | Stored positive control and DB delay | Version receipt | Exact restore and delayed reread |\n| --- | --- | --- | --- |\n']
for phase,label in [('master-primary','Master primary'),('master-german-final','Master German'),('channel-pin','Channel operator pin')]:
 request=read(f'request-{phase}.json');snap=read(f'fixture-{phase}.json');restore=read(f'restore-{phase}.json');again=read(f'fixture-{phase}-restored.json')
 from datetime import datetime as D
 dt=lambda v:D.fromisoformat(v.replace('Z','+00:00'))
 delay=(dt(snap['at'])-dt(request['writtenAt'])).total_seconds()
 version=f"{'Listing' if phase=='channel-pin' else 'Product'} {request['body']['expectedVersion']}→{request['result']['currentVersion']}"
 if phase!='master-primary':version+='; '+('pin' if phase=='channel-pin' else 'translation')+' absent→1'
 lines.append(f"| {label} | `{request['body']['changes'][0]['value']}`; {request['writtenAt']} → {snap['at']} (**{delay:.3f}s**) | {version} | {restore['at']}; baseline exact at {again['at']} |\n")
for phase,label in [('acknowledged-shared','Channel acknowledged to shared'),('drift-cell','Drift cell acknowledged to shared')]:
 receipt=read(f'receipt-{phase}.json');restore=read(f'restore-{phase}.json');again=read(f'fixture-{phase}-restored.json')
 lines.append(f"| {label} | UI acknowledgement; {receipt['writtenAt']} → {receipt['readAt']} (**{receipt['delayMs']/1000:.3f}s**) | Product 1→2; German translation absent→1; listing 18→19 | {restore['at']}; baseline exact at {again['at']} |\n")
d=read('decline-receipt.json')
lines.append(f"| Decline reverts | UI Cancel at {d['declinedAt']}; DB at {d['readAt']} (**{d['delayMs']/1000:.3f}s**) | Zero write requests, zero data differences and zero version bumps against the prepared inherited cell | Original displayed value restored; prompt stayed closed; inherited setup removed with acknowledged-path restore and reread above |\n")
lines += ['\nThe inherited-cell setup was an addressed reset: listing 17→18 and one new following marker. The drift setup changed only `followMasterTitle` false→true plus listing 17→18, because the family had no existing following text snapshots. The drift wire explicitly reported `channelSnapshot`, follows=true, pinned=false, contentAddress=null and both choices. Both setups were restored to the original listing version 17 and follow flag false. Restores reinstated captured values, versions and timestamps with a comparison against the last receipt; all rehearsal-created translation/follow-marker/queue rows were removed. The original English translation, legacy listing title/description and Product.localizedContent stayed byte-for-value unchanged. Audit history is retained. Final delayed fixture reread 15:03:20.661Z: baseline exact in all six inspected tables. Final read-only audit at 15:12:45.048Z: 11 audit rows, language de=10 / it=1, zero remaining rehearsal queues and no read-only trigger; transaction rolled back. Owned rehearsal servers were stopped.\n',
'**Screen reading.** On Amazon · DE, Title above the grid showed **“Choose where to save this text”**, **“Write the shared German (new)” / “Pin on Amazon · DE · de” / “Cancel”**, and the reach **Amazon · DE (de)**. Drift showed **“Edit the shared German” / “Pin on Amazon · DE · de” / “Cancel”**. Both answers were visible; keyboard Enter accepted the drift shared choice. The saved cell then said **“Reviewed translation. de content has been reviewed.”** Evidence: [light acknowledgement](audits/2026-09-12-language-axis/step4/acknowledgement-light.png), [dark drift acknowledgement](audits/2026-09-12-language-axis/step4/drift-acknowledgement-dark.png), `drift-wire.json`, `decline-receipt.json`, `receipt-acknowledged-shared.json`, `receipt-drift-cell.json`. Host rendering: `apps/web/src/app/products/[id]/edit/_studio/sheet/channel/ChannelSheet.tsx` (acknowledgement/decline handler); service routing: `apps/api/src/services/pim/studio-sheet.service.ts` (`resolveWriteRouting`). The Languages view remains Step 6.\n',
'**Defects found and fixed before stopping.** (1) A newly reviewed translation initially appeared outdated because the reader fingerprint included extra schema fields; writer/reader now hash the same authored field set and the regression test passes. The first German UI save was restored, then the corrected positive control was repeated. (2) The acknowledgement initially overflowed the toolbar; it now occupies a full row above the grid. (3) Cancel initially re-armed the prompt through a deferred AG `setDataValue` event; it now mutates/restores the row and refreshes without emitting an edit. The final decline measurement confirms zero requests, unchanged versions and a closed prompt. Slot pastes keep each position; a mixed Shopify/bulk predicate was corrected to retain all cells. No machine copy was published.\n',
'**Tests and checks.** Final API run: 8 files / **95 passed**, including 12 disposable PostgreSQL tests, actual bulk entry point, slot preservation, parent-language cascade, named refusals, review/CAS, pin isolation, explicit clear/reset and Belgium nl/fr independence; built-payload language-tag tests remain green. Final web run: 3 files / **40 passed**, including one shared address wire contract, typed/paste/fill gates, correct Product/listing CAS and verbatim server sentences. Final scoped typecheck: 26 API and 11 web input files plus their transitive imports, exit **0**; shared ContentAddress output was built and Prisma client generated successfully. `git diff --check` exit **0**. Final API socket run initially hit sandbox EPERM; the authorized retry passed, with the failed attempt retained in `api-sandbox-attempt.*`.\n',
f'**Guard output:** `LX.2`, **{guard["scanned"]}** tracked/untracked API sources scanned; **0 violations**; 13 protected runtime exemptions retained, including the Owner-named flat-file and amazon-batch-feed exemptions. Full output: [guard-output.json](audits/2026-09-12-language-axis/step4/guard-output.json). All **16** protected file hashes match the Step 4 starting snapshot. SDK diagnostics/in-flight files were not changed. Step 3 shadow instrumentation is retained; no production catalogue shadow was re-run during Step 4.\n',
'**Q-LX4-1 — open, required gate input.** `node scripts/check-editor-open.mjs --strict` reached the local server at 16:53:10 Europe/Rome and exited **2**, before editor measurements: “A signed-in studio session is required.” The runner at `scripts/studio-browser-auth.mjs:5–20` requires an existing dedicated test storage-state path or normal test-login configuration. The asynchronous question asking which existing configuration to use remains unanswered. Recommendation: supply the existing local test account/session through `STUDIO_STORAGE_STATE` or `STUDIO_TEST_EMAIL`/`STUDIO_TEST_PASSWORD`; do not export the interactive browser session or bypass authentication. [Gate log](audits/2026-09-12-language-axis/step4/editor-open.log). **No strict-gate green is claimed, so Step 4 is not closed.** The isolated screen/fixture evidence above does not substitute for that gate.\n',
'**Source receipt.** The following files changed relative to the claimed Step 4 starting bytes, preserving earlier uncommitted work. Full pre-edit bytes in `before.json`; exact Step 4-only diff in [step4-source.diff](audits/2026-09-12-language-axis/step4/step4-source.diff). No commit, push or deployment was made.\n',
'| File | mtime (UTC) | SHA256 |\n| --- | --- | --- |\n']
for item in manifest:lines.append(f"| `{item['file']}` | {item['mtime']} | `{item['sha256']}` |\n")
record=''.join(lines)
assert '## Language axis · Step 4 · §4 record' not in ledger.read_text(),'Do not append a second Step 4 report.'
line=len(ledger.read_text().splitlines())+2
with ledger.open('a') as f:f.write(record)
(here/'record-location.json').write_text(json.dumps({'file':'docs/pes-claims.md','line':line,'at':now,'status':'gate-open-awaiting-test-login'},indent=2)+'\n')
# Artifact inventory, excluding the self-referential inventory and live shared ledger.
artifacts=[]
for p in sorted(here.rglob('*')):
 if p.is_file() and p.name!='artifact-manifest.json' and 'node_modules' not in p.parts:
  artifacts.append({'file':str(p.relative_to(root)),'mtime':datetime.fromtimestamp(p.stat().st_mtime,timezone.utc).isoformat(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(here/'artifact-manifest.json').write_text(json.dumps(artifacts,indent=2)+'\n')
print(json.dumps({'recordLine':line,'sourceFiles':len(manifest),'artifactFiles':len(artifacts),'tests':135,'strictGateExit':2,'status':'Step 4 open'}))
