const { default: prisma } = await import('../src/db.js')
const regal = await prisma.product.findMany({ where: { sku: { contains: 'REGAL' } }, select: { id:true, sku:true, parentId:true } })
const ids = regal.map(r=>r.id)
const levels = await prisma.stockLevel.findMany({ where: { productId: { in: ids }, location: { type:'WAREHOUSE' } }, select: { productId:true, available:true, location:{select:{code:true}} } })
const byPid = new Map<string, number>()
for (const l of levels) byPid.set(l.productId, (byPid.get(l.productId)??0)+l.available)
console.log('REGAL products:', regal.length, 'with warehouse rows:', byPid.size)
for (const r of regal) if (byPid.has(r.id)) console.log('  HAS ROWS', r.sku, byPid.get(r.id))
const noRow = regal.filter(r=>!byPid.has(r.id))
console.log('  NO warehouse row at all:', noRow.length, 'e.g.', noRow.slice(0,5).map(r=>r.sku).join(', '))
await prisma.$disconnect()
