/** READ-ONLY: any DE residue left after deleting the eBay/DE ChannelListing rows? */
const { default: prisma } = await import('../src/db.js')
const q = await prisma.outboundSyncQueue.count({ where: { targetRegion: 'DE' } })
const qEbay = await prisma.outboundSyncQueue.count({ where: { targetRegion: 'DE', targetChannel: 'EBAY' } })
const qLive = await prisma.outboundSyncQueue.count({ where: { targetRegion: 'DE', externalListingId: '257584954808' } })
const liveImg = await prisma.channelLiveImage.count({ where: { channel: 'EBAY', marketplace: 'DE' } })
const memb = await prisma.sharedListingMembership.count({ where: { marketplace: 'DE' } })
const cl = await prisma.channelListing.count({ where: { channel: 'EBAY', marketplace: 'DE' } })
console.log(`eBay/DE ChannelListing rows           : ${cl} (expect 0)`)
console.log(`OutboundSyncQueue targetRegion=DE     : ${q}  (EBAY: ${qEbay})`)
console.log(`  …of those aimed at LIVE IT 257584954808: ${qLive} (expect 0)`)
console.log(`ChannelLiveImage EBAY/DE              : ${liveImg}`)
console.log(`SharedListingMembership marketplace=DE: ${memb} (was always 0)`)
await prisma.$disconnect()
