/** HV-R P3a — prove the pathway service against prod. READ-ONLY. */
import '../src/env.js'
const { listHarvestPathways } = await import('../src/services/advertising/harvest-pathways.service.js')
const p = await listHarvestPathways()
console.log(`\n═══ totals ═══`)
console.log(JSON.stringify(p.totals, null, 1))
const byRole = new Map<string, number>()
for (const s of p.sources) byRole.set(s.role ?? '?', (byRole.get(s.role ?? '?') ?? 0) + 1)
console.log(`\nsources by role: ${[...byRole].map(([k,v])=>`${k} ${v}`).join(' · ')}`)
const byProd = new Map<string, number>()
for (const s of p.sources) byProd.set(s.adProduct ?? '?', (byProd.get(s.adProduct ?? '?') ?? 0) + 1)
console.log(`sources by adProduct: ${[...byProd].map(([k,v])=>`${k} ${v}`).join(' · ')}`)
const byMkt = new Map<string, number>()
for (const s of p.sources) byMkt.set(s.marketplace ?? '?', (byMkt.get(s.marketplace ?? '?') ?? 0) + 1)
console.log(`sources by market: ${[...byMkt].map(([k,v])=>`${k} ${v}`).join(' · ')}`)
console.log(`sources with NO amazon id (local only): ${p.sources.filter(s=>!s.externalAdGroupId).length}`)
console.log(`\n🔴 did the roleOf fallback actually add anything? sources whose NAME says nothing:`)
const nameless = p.sources.filter(s => !/AUTO|EXACT|PHRASE|BROAD/i.test(s.name))
console.log(`   ${nameless.length} of ${p.sources.length}`)
for (const s of nameless.slice(0,8)) console.log(`   [${s.role}] "${s.name}" · ${s.campaignName} · mt=[${s.matchTypes.join(',')}]`)
console.log(`\nsample destinations (${p.destinations.length}):`)
for (const d of p.destinations.slice(0,5)) console.log(`   "${d.name}" · ${d.campaignName} (${d.marketplace}, ${d.campaignStatus})`)
const { default: prisma } = await import('../src/db.js'); await prisma.$disconnect()
