const { PrismaClient } = await import('@prisma/client')
const p = new PrismaClient({ datasources: { db: { url: process.argv[2] } } })
const j = (v: unknown) => JSON.stringify(v, (_k, x) => (typeof x === 'bigint' ? Number(x) : x))
console.log('Product workspaceIds:', j(await p.$queryRawUnsafe(`SELECT "workspaceId", count(*)::int n FROM "Product" GROUP BY 1`)))
console.log('ChannelListing workspaceIds:', j(await p.$queryRawUnsafe(`SELECT "workspaceId", count(*)::int n FROM "ChannelListing" GROUP BY 1`)))
console.log('StockLocation IT-MAIN:', j(await p.$queryRawUnsafe(`SELECT id, code, type, "workspaceId" FROM "StockLocation" WHERE code='IT-MAIN'`)))
console.log('XAVIA root familyId/productType:', j(await p.$queryRawUnsafe(`SELECT id, sku, "familyId", "productType", "workspaceId", "variationAxes" FROM "Product" WHERE sku='xavia-knee-slider'`)))
console.log('RLS on ChannelListing?', j(await p.$queryRawUnsafe(`SELECT relname, relrowsecurity, relforcerowsecurity FROM pg_class WHERE relname IN ('ChannelListing','Product','StockLevel')`)))
await p.$disconnect()
