import prisma from '../src/db.js'
const since = new Date('2026-08-26T09:35:00Z')
console.log('=== settings-sync runs since 09:35 ===')
for (const r of await prisma.cronRun.findMany({ where: { jobName: 'ads-campaign-settings-sync', startedAt: { gte: since } }, orderBy: { startedAt: 'asc' }, select: { startedAt: true, status: true, outputSummary: true } }))
  console.log(`  ${r.startedAt.toISOString().slice(11,19)} ${r.status} ${r.outputSummary}`)
console.log('\n=== AdMutation columns ===')
const cols = await prisma.$queryRawUnsafe<any[]>(`SELECT column_name, data_type FROM information_schema.columns WHERE table_name='AdMutation' ORDER BY ordinal_position`)
console.log('  ' + cols.map((c) => c.column_name).join(', '))
console.log('\n=== AdMutation rows for CAMPAIGN status since 09:35 ===')
const m = await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "AdMutation" WHERE "entityType"='CAMPAIGN' AND field='status' AND "createdAt" >= $1 ORDER BY "createdAt" ASC LIMIT 5`, since)
for (const r of m) console.log('  ' + JSON.stringify(r).slice(0, 320))
console.log(`  (total: ${(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int n FROM "AdMutation" WHERE "entityType"='CAMPAIGN' AND field='status' AND "createdAt" >= $1`, since))[0].n})`)
console.log('\n=== unsettled AdMutation rows overall (these HOLD BACK the sync) ===')
const u = await prisma.$queryRawUnsafe<any[]>(`SELECT field, "settledAt" IS NULL AS unsettled, COUNT(*)::int n FROM "AdMutation" WHERE "entityType"='CAMPAIGN' GROUP BY 1,2 ORDER BY 3 DESC LIMIT 12`).catch((e) => { console.log('  (no settledAt col):', String(e).slice(0,120)); return [] })
for (const r of u) console.log(`  ${String(r.field).padEnd(18)} unsettled=${r.unsettled} n=${r.n}`)
await prisma.$disconnect()
