const { default: prisma } = await import('../src/db.js')
console.log(`orphaned AdTargets now: ${await prisma.adTarget.count({ where: { orphanedAt: { not: null } } })}`)
const moss = await prisma.adTarget.findMany({ where: { adGroup: { campaign: { name: 'Auto_Close_Moss' } } }, select: { kind: true, expressionType: true, externalTargetId: true, orphanedAt: true, orphanReason: true, lastSyncStatus: true, status: true, bidCents: true } })
console.log(`\nAuto_Close_Moss targets (${moss.length}):`)
for (const t of moss) console.log(`  ${t.kind}/${t.expressionType} ext=${t.externalTargetId} orphaned=${t.orphanedAt ? 'YES' : 'no'} reason=${t.orphanReason ?? '—'} sync=${t.lastSyncStatus} bid=${t.bidCents}`)
const cr = await prisma.cronRun.findMany({ where: { jobName: 'ad-rank-defend' }, orderBy: { startedAt: 'desc' }, take: 3, select: { startedAt: true, status: true, outputSummary: true } })
console.log('\nrecent ad-rank-defend runs:')
for (const c of cr) console.log(`  ${c.startedAt.toISOString()} ${c.status} — ${c.outputSummary}`)
const H2 = new Date(Date.now() - 2 * 3600 * 1000)
const fails = await prisma.adMutation.count({ where: { state: 'FAILED', updatedAt: { gte: H2 } } })
const oks = await prisma.adMutation.count({ where: { state: 'APPLIED', updatedAt: { gte: H2 } } })
console.log(`\nlast 2h mutations: APPLIED=${oks} FAILED=${fails}`)
const q = await prisma.outboundSyncQueue.groupBy({ by: ['syncType'], where: { syncStatus: 'FAILED' }, _count: { _all: true } })
console.log('remaining FAILED queue rows:', q.map((x) => `${x.syncType}=${x._count._all}`).join(' '))
await prisma.$disconnect()
