-- Additive: a new table. Durable Idempotency-Key receipts for commands that a
-- double-click must not run twice (apps/api/src/lib/command-idempotency.ts).
CREATE TABLE "CommandReceipt" (
  "workspaceId" TEXT NOT NULL DEFAULT NULLIF(current_setting('nexus.workspace_id', true), ''),
  "id" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "keyHash" TEXT NOT NULL,
  "requestHash" TEXT NOT NULL,
  "actorUserId" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "httpStatus" INTEGER,
  "response" JSONB,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "CommandReceipt_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "CommandReceipt_workspaceId_scope_keyHash_key" ON "CommandReceipt"("workspaceId", "scope", "keyHash");
CREATE INDEX "CommandReceipt_workspaceId_expiresAt_idx" ON "CommandReceipt"("workspaceId", "expiresAt");
-- Business isolation, generated by scripts/workspace-policies.mjs workspaceModelSql("CommandReceipt").
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "CommandReceipt" TO nexus_workspace_runtime;
ALTER TABLE "CommandReceipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommandReceipt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS nexus_workspace_isolation ON "CommandReceipt";
CREATE POLICY nexus_workspace_isolation ON "CommandReceipt" FOR ALL TO nexus_workspace_runtime USING (("workspaceId" = NULLIF(current_setting('nexus.workspace_id', true), '') AND EXISTS (SELECT 1 FROM "Workspace" w WHERE w.id = "CommandReceipt"."workspaceId" AND w.status = 'active'
      AND (NULLIF(current_setting('nexus.actor_id', true), '') IS NULL OR EXISTS (
        SELECT 1 FROM "WorkspaceMembership" m JOIN "UserProfile" u ON u.id = m."userId"
        WHERE m."workspaceId" = w.id AND m."userId" = current_setting('nexus.actor_id', true)
          AND m.status = 'active' AND u.status = 'active'))))) WITH CHECK (("workspaceId" = NULLIF(current_setting('nexus.workspace_id', true), '') AND EXISTS (SELECT 1 FROM "Workspace" w WHERE w.id = "CommandReceipt"."workspaceId" AND w.status = 'active'
      AND (NULLIF(current_setting('nexus.actor_id', true), '') IS NULL OR EXISTS (
        SELECT 1 FROM "WorkspaceMembership" m JOIN "UserProfile" u ON u.id = m."userId"
        WHERE m."workspaceId" = w.id AND m."userId" = current_setting('nexus.actor_id', true)
          AND m.status = 'active' AND u.status = 'active')))));
DROP TRIGGER IF EXISTS nexus_workspace_references ON "CommandReceipt";
CREATE TRIGGER nexus_workspace_references BEFORE INSERT OR UPDATE ON "CommandReceipt" FOR EACH ROW EXECUTE FUNCTION nexus_workspace_reference_guard('[]');
